### ISSUE TITLE
feat(open-digital-asset): building open-digital-asset(odap) on top of cactus

### ISSUE THREAD

**Issue by jscode017** [hyperledger/cacti#1025]
Is your feature request related to a problem? Please describe.
Building odap: https://datatracker.ietf.org/doc/draft-hargreaves-odap/ to create odap gateways, enable the client to interact with distributed ledger. See figure 1 of the odap draft for basic work flow.

Cactus implements the technical and syntactic layer regarding blockchain interoperability. Technical and syntactic layer enable negotiation between parties on different ledgers and provide reliable transfer protocol. 
However, cactus currently lacks support for the semantic layer. The semantic layer would standardize asset transfer, message format, identity proof, and ledger state-transfer proof. With the semantic layer, we could enable semantic compatibility between different ledgers, to provide a more cross-chain-app friendly infrastructure.

So we propose building odap — _standardization effort from IETF, trying to transfer assets across jurisdictions_ — on top of cactus to provide
- Types of API #1027
- Types of flows #1028
- Format of exchanging message #1026 
- Format of digital asset resource descriptors
- Format of digital asset resource client descriptors
- Steps and format of security protocols and parameters negotiation
- Steps and format of asset profile negotiation
- Steps and format of application profile negotiation
- API and implementation to access resources
- Type of actions to assets

And after this, we would propose and build a cross-chain dapp on top of odap, to showcase how cactus could be benefit from odap.
@petermetz, @RafaelAPB, @ruychi

**Comment by AndreAugusto11** [comment]
@petermetz this issue (and the respective sub-issues related to the odap plugin) should be closed because the functionality described is already implemented
