### ISSUE TITLE
feat(Validator): add the docker environment of Validators and its applications

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cacti#1083]
**Is your feature request related to a problem? Please describe.**
To adapt Validators to some custom ledgers, the docker environment of Validators are more useful to setup than the raw application (e.g. to use custom TLS-off Fabric ledgers instead of default Fabric ledgers).

**Describe the solution you'd like**
To add the docker environment of Validators

**Comment by petermetz** [comment]
@takeutak Has this been completed in the meantime or are you still working on it?
