### ISSUE TITLE
feat(htlc-coordinator): new coordinator implementation

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#1180]
### Description
As a developer, I want to implement another HTLC coordinator example as per @sfuji822 explanation mentioned [here](https://github.com/hyperledger/cactus/issues/603#issuecomment-872403657)

(Quoted from the above referenced chat)
If the Cactus will play the role as the intermediate on the asset trade between Alice and Bob, the HTLC address should be notified and assist in interactions with HTLC because both Alice and Bob cannot trust Cactus as fund receiver in this use case.

1. Bob instantiates HTLC Coordinator with Alice's address information
2. Bob receives the handle of the HTLC Coordinator and the address of HTLCs
3. Bob invokes HTLC-1 with hashed-time-lock with expiration-1(given by Cactus)
4. Alice invokes HTLC-2 with hashed-time-lock with expiration-2(given by Cactus)
5. Bob invokes HTLC-2 to withdraw funds from Alice
6. HTLC Coordinator invokes HTLC-1 to withdraw funds from Bob using observed transaction

### Acceptance Criteria
1. The implementation should be in accordance to the above use-case.

cc: @sfuji822 @kikoncuo @petermetz @jonathan-m-hamilton

**Comment by sfuji822** [comment]
I am sorry to keep this issue open.

I believe you assumed cactus does not have any privilege regarding this Atomic Swap, right?
I interpreted your intended feature on Coordinator as follows:
The coordinator can set the right values for time-lock on both HTLCs.
The coordinator invokes HTLC-1 to execute asset deposits by Bob.
The coordinator also invokes HTL-2 to execute asset deposits by Alice.
Finally, the coordinator accepts the hash value from Bob to unlock HTLC-1 and HTLC-2 same time, and funds will be transferred to Alice and Bob.

Please note Alice can cancel the swap only when she does not execute the deposit on HTLC-2.
Thus we should add  one more requirement on acceptance criteria:
time-lock value for HTLC-2 is set to prevent Bob's cancel of his deposit on HTLC-1 before he exposes hash-value to unlock HTLCs.
In another word, the coordinator should set a time-lock on HTLC-2 for allowing Alice to cancel her deposit when Bob did not send the hash.

Does this make sense to you?

@jagpreetsinghsasan @kikoncuo @petermetz @jonathan-m-hamilton @takeutak @izuru0

**Comment by petermetz** [comment]
@sfuji822 No problem, thank you for getting around to it! I'll ask Jagpreet to chime in. @jagpreetsinghsasan Please discuss, let me know if you need any help!

**Comment by jagpreetsinghsasan** [comment]
Thanks @sfuji822 for the clarification
Regarding your point
> In another word, the coordinator should set a time-lock on HTLC-2 for allowing Alice to cancel her deposit when Bob did not send the hash.

The point 4 of the above description confirms your point (correct me if I am wrong there).
