### ISSUE TITLE
feat(cc-tx-viz): add plugin for visualization of cross-chain transactions

### ISSUE THREAD

**Issue by maramih** [hyperledger/cacti#1214]
**Is your feature request related to a problem? Please describe.**
Hyperledger blockchain developers only have vague understanding to the performance and scalability of the crosschain transactions with Cactus and currently, there is no efficient way to visualize or measure the performance of cross blockchain transactions with Cactus.

**Describe the solution you'd like**
We propose creating a new package in order to provide visualization for the cross-chain transactions.
So, to implement this package we need to:

- Extend connectors #1215 
- Gather metrics #1216 
- Implement UI

**Describe alternatives you've considered**
Manually inspect each ledger metrics.

@takeutak @sfuji822 @petermetz @jonathan-m-hamilton @hartm @RafaelAPB

**Comment by maramih** [comment]
I'm working on this.

**Comment by petermetz** [comment]
@maramih Thank you very much! If you need any help please free to join one of our daily pair programming calls that's on the calendar. See the wiki for more details: https://wiki.hyperledger.org/display/cactus

**Comment by outSH** [comment]
@maramih Is anyone still working on this?

**Comment by RafaelAPB** [comment]
@outSH  we have finished this project. code and paper are available here: https://www.techrxiv.org/doi/full/10.36227/techrxiv.20718058.v3

**Comment by RafaelAPB** [comment]
@petermetz we can close this
