### ISSUE TITLE
fix(indy-validator): pool initialization code is missing

### ISSUE THREAD

**Issue by izuru0** [hyperledger/cacti#1266]
**Describe the bug**

The validator fails to start

**To Reproduce**

1. cd to tools/docker/indy-testnet and docker-compose up
2. log into valdiator container using docker exec
3. run python -m main to start the server

**Expected behavior**

The server starts without an error.

**Actual behavior**

The validator fails to open the pool and fails to start.

The validator server opens a pool on startup using indy-sdk API pool.open_pool_ledger, which expects a file (/tmp/indy/pool1.txn) to exist before it is called.

However, initialization code to create the file is missing.

**Comment by outSH** [comment]
Fixed by https://github.com/hyperledger/cacti/pull/1267
