### ISSUE TITLE
docs(ledger-support-matrix): add ledger support document for go-Ethereum, sawtooth, indy

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cacti#1321]
**Is your feature request related to a problem? Please describe.**
Cactus has ledger-connectors for go-Ethereum, sawtooth, and indy. But their ledger-support document is not described yet.

**Describe the solution you'd like**
@takeutak will add the above document.

**Comment by petermetz** [comment]
@takeutak Is there end to end test coverage for any of these components?

**Comment by petermetz** [comment]
Fixed by #1279
