### ISSUE TITLE
perf: enable Webpack Persistent Caching for Builds

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#139]
**Is your feature request related to a problem? Please describe.**
Builds are slow. Performance is a feature. ;-)

**Describe the solution you'd like**
Faster builds. (`npm run build`)

**Describe alternatives you've considered**
Also looking into tools that monitor the file system for changes, but it's hard to integrate those into our build pipeline directly because they aren't specific to Javascript/NodeJS ES modules.

**Additional context**

These would be really nice to leverage:
1. https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md
2. Only generate bundle size analytics report when flag is present (e.g. make it opt-in vs. the current default ON)

**Comment by takeutak** [comment]
I'm sure that development milestones (such as "v0.2.0") will be discussed at the Cactus meeting.  Could you mind if you delete such commits from this PR?
 * https://github.com/hyperledger/cactus/projects/1#card-38540731

**Comment by petermetz** [comment]
> I'm sure that development milestones (such as "v0.2.0") will be discussed at the Cactus meeting. Could you mind if you delete such commits from this PR?
> 
> * https://github.com/hyperledger/cactus/projects/1#card-38540731

@takeutak Sure, removed it. 👍

**Comment by petermetz** [comment]
We plan to switch out webpack to either esbuild or ncc or a combination of them so this is no longer relevant.
