### ISSUE TITLE
fix(tools): fix the bug related with the old key on the directory of tools/docker/ fabric ledger

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cacti#1407]
**Describe the bug**

The fabric ledger including fabcar chaincode cannot work well due to the expire date of the old key on the directory of /tools/docker/...
- related with #1311

**To Reproduce**

I will change the boot script to use the new key which is generated when the ledger is launched.

**Comment by outSH** [comment]
I think this is not an issue in current asset-trade version
