### ISSUE TITLE
feat(connector-iroha-socketio): add the testclient for sendAsyncRequest on iroha-connector-socketio

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cacti#1431]
**Is your feature request related to a problem? Please describe.**
There is a lack of testclient for sendAsyncRequest on iroha-connector-socketio

**Describe the solution you'd like**
@takeutak will add this feature

**Comment by takeutak** [comment]
This EPIC is #1525

**Comment by petermetz** [comment]
> This EPIC is #1525

@takeutak Set the epic to #1525 in ZenHub as you mentioned.
