### ISSUE TITLE
feat(connector-sawtooth-socketio): add sendSyncRequest on connector-sawtooth-socketio

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cacti#1432]
**Is your feature request related to a problem? Please describe.**
There is a lack of sendSyncRequest (e.g. get parameter) and sendAsyncRequest (e.g. sendTransaction) on connector-sawtooth-socketio

**Describe the solution you'd like**
@takeutak will add sendSyncRequest on connector-sawtooth-socketio

**Comment by takeutak** [comment]
Its EPIC is #1524

**Comment by petermetz** [comment]
> Its EPIC is #1524

@takeutak I set the epic of this to be #1524 in ZenHub as you mentioned.
