### ISSUE TITLE
build: upgrade to Node 16 LTS (16.13.0)

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1483]
### Description

https://nodejs.org/en/blog/release/v16.13.0/

### Acceptance Criteria
1. The CI runs on `16.13.0`
2. Dev container is updated to use `16.13.0` 
3. cmd-api-server container image is upgraded to use `16.13.0` as well
3. All the other container images are also updated have Node installed in them to use `16.13.0`

**Comment by ironbyte** [comment]
Hi, happy to take up this issue. Please assign me to it, thanks.

**Comment by petermetz** [comment]
@ironbyte All yours, thank you very much for the contribution in advance!

**Comment by ironbyte** [comment]
Awesome, thanks! ^^

**Comment by petermetz** [comment]
This has been fixed in the meantime.
