### ISSUE TITLE
[EPIC] connection chain code consolidation

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1497]
### Description

As a maintainer I want to have packages that do not duplicate existing functionality so that it's easier to maintain the code, needs less documentation and newcomers can better understand what's going on in terms of individual package responsibilities.

This is a reboot of https://github.com/hyperledger/cactus/pull/719 which was opened in the Spring of 2021 and then went nowhere for 5 months with finally all the original work getting deleted from it completely.

Most of the issues within this epic will apply equally to all of these packages:
```
- packages:
  - cactus-cmd-socketio-server
  - cactus-plugin-ledger-connector-go-ethereum-socketio
  - cactus-plugin-ledger-connector-fabric-socketio
  - cactus-plugin-ledger-connector-sawtooth-socketio
```

**Comment by izuru0** [comment]
Refactoring to reduce redundancy is acceptable if functionalities provided by existing modules (e.g. monitoring functionality provided by startMonitor/stopMonitor API in cactus-cmd-socketio-server) are not removed.

In particular, the following functionalities described in the API table are needed.
- Verifier API (= Cactus API)
  - sendAsyncRequest: transfer signed transactions into validator
  - sendSyncRequest: transfer synchronized request into validator
  - startMonitor: transfer request to start continuous monitoring of blocks into validator
  - stopMonior: transfer request to stop continuous monitoring of blocks into validator
- Validator API (= Ledger Connector API)
  - sendAsyncRequest: issue signed transaction to ledger
  - sendSyncRequest: send synchronized request to ledger and receive the return
  - startMonitor: start continuous monitoring of blocks
  - stopMonitor: stop continuous monitoring of blocks

* cf.: API table: https://github.com/hyperledger/cactus/blob/main/whitepaper/whitepaper.md
* cf.: implementation: https://github.com/hyperledger/cactus/blob/main/packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts

**Comment by takeutak** [comment]
@petermetz Thanks for @izuru0's comment about the above API.  Please let me add more information.

We also need to the functionality of posting transactions and getting transaction information and status described as the following whitepaper
 - https://github.com/hyperledger/cactus/blob/main/whitepaper/whitepaper.md#531-cactus-service-api
The current codes are here (sorry these are in example directory, we will plan to refactor to move this feature on the cactus-socket-server)
 - https://github.com/hyperledger/cactus/blob/main/examples/cartrade/trades.ts#L26

The above are only part of those functionalities and I will add the other functionalities we already developed on this comment later. After finishing our preparations, I'm happy that we will discuss about the API design.

**Comment by petermetz** [comment]
@takeutak @izuru0 I responded to your emails.

**Comment by outSH** [comment]
All of these modules have been refactored and/or deprecated - closing
