### ISSUE TITLE
refactor: tsconfig.json uniform structure

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1498]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

Make sure that all the outlier packages have their tsconfig.json file:
1. adhere to the general structure, includes, excludes, etc.
2. is compatible with the rest of the files so that the sync npm deps (see `./tools` folder) can be executed without it generating a diff
3. inherits from the same tsconfig as the rest of the packages (`./tsconfig.base.json` in the root dir)

[1]: root package.json => `"sync-ts-config": "TS_NODE_PROJECT=tools/tsconfig.json node --experimental-json-modules --loader ts-node/esm ./tools/sync-npm-deps-to-tsc-projects.ts",`

**Comment by outSH** [comment]
Done for two remaining packages:
  - cactus-cmd-socketio-server
  - cactus-plugin-ledger-connector-go-ethereum-socketio
