### ISSUE TITLE
refactor: package.json uniform structure

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1499]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

Make sure the outlier packages have package.json files that are in accordance with the default pattern we have in terms of 
1. build scripts, 
2. watch scripts, 
3. exports declarations, 
4. typings declarations, 
5. etc (all the properties that we use in the package.json file)

**Comment by outSH** [comment]
Done for two remaining packages:
  - cactus-cmd-socketio-server
  - cactus-plugin-ledger-connector-go-ethereum-socketio
