### ISSUE TITLE
refactor: linter warnings eliminated

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1500]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

Eliminate the need for the following ESLint ignore rules:

```sh
packages/cactus-verifier/src/main/typescript/

packages/cactus-cmd-socketio-server/**
packages/cactus-plugin-ledger-connector-sawtooth-socketio/**
packages/cactus-plugin-ledger-connector-go-ethereum-socketio/**
packages/cactus-plugin-ledger-connector-*-socketio/**
```

For reference/guidance on how to do it: The work for this was already done in #719 but then got deleted.

**Comment by outSH** [comment]
Plugins refactored
