### ISSUE TITLE
refactor(connector-fabric-socketio): merge into connector-fabric

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1503]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

socketio has been supported since May via #897, the work was done specifically to address the old code integration concerns so that a separate package/code is not needed.

[1]: https://github.com/hyperledger/cactus/pull/897

**Comment by outSH** [comment]
Done
