### ISSUE TITLE
refactor(connector-sawtooth-socketio): implement core-api interfaces

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1504]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

Implement the connector interfaces:
1. factory creator function export
2. factory class itself
3. plugin class to implement the cactus plugin interface
4. plugin class to implement the web service plugin interface
5. tests to verify that it works within cmd-api-server

**Comment by outSH** [comment]
Done
