### ISSUE TITLE
refactor(go-ethereum-socketio): implement core-api interfaces

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1505]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

Depends on #1506 (not really a hard dependency, more of a recommendation that these two issues should not be worked on simultaneously because that will lead to nasty conflicts)

Implement the connector interfaces:
1. factory creator function export
2. factory class itself
3. plugin class to implement the cactus plugin interface
4. plugin class to implement the web service plugin interface
5. tests to verify that it works within cmd-api-server

**Comment by outSH** [comment]
Plugin refactored
