### ISSUE TITLE
refactor(go-ethereum-socketio): rename to go-ethereum

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1506]
See the containing epic for more context and the scope of packages that are being affected: https://github.com/hyperledger/cactus/issues/1497

---

Depends on #1505 (not really a hard dependency, more of a recommendation that these two issues should not be worked on simultaneously because that will lead to nasty conflicts)

The go-ethereum package could contain common code that could be re-used by all the eth flavored connectors such as xdai, besu, quorum.

**Comment by outSH** [comment]
Plugin refactored
