### ISSUE TITLE
feat(cartrade): support more environments

### ISSUE THREAD

**Issue by t-yasushi** [hyperledger/cacti#1512]
Some environments (ex. not centos) have problems with fabcar operation, so make the cartrade application available in more environments.

The environment that we are planning to support here in addition to CentOS:
- Ubuntu

**Comment by t-yasushi** [comment]
@t-yasushi  I'd like to work this.

**Comment by petermetz** [comment]
Hello world

**Comment by petermetz** [comment]
@t-yasushi Thank you, assigned it to you just now!

cc: @hartm @takeutak

**Comment by outSH** [comment]
Closed with #1592
