### ISSUE TITLE
test(besu): fix flake in private-deploy-contract-from-json-cactus

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1543]
**Describe the bug**

The test `packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-cactus.test.ts` is flaky.

**To Reproduce**

Run it in a low resource environment such as by modifying the dev container to limit itself in memory usage:

**.devcontainer/devcontainer.json**:

```json
"name": "Ubuntu 20.04 - Docker in Docker",
"runArgs": ["--init", "--privileged", "--memory=7g", "--memory-swap=17g", "--cpus=2",],
```

**Expected behavior**

Test passes every time.

**Logs/Stack traces**

[2021-11-16_ci.log](https://github.com/hyperledger/cactus/files/7551589/2021-11-16_ci.log)

**Cloud provider or hardware configuration:**

Dev machine -> dev container with the low resource configuration explained above.

**Operating system name, version, build:**

Ubuntu 20.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`1.0.0-rc.2`

**Hyperledger Cactus Plugins/Connectors Used**

Besu

**Comment by ashnashahgrover** [comment]
I modified the dev container as explained above, but did not get the same error outlined in the log file attached - I got no error and all the tests passed.

**Comment by petermetz** [comment]
@ashnashahgrover Thank you, I'm closing this one for now in that case. If it starts flaking again we can revisit the issue.
