### ISSUE TITLE
fix(cactus-cmd-socketio-server): aggregates signature schemes for fabric

### ISSUE THREAD

**Issue by t-yasushi** [hyperledger/cacti#1627]
Describe the bug

The Signature in fabric takes place in two steps: "Endorse" and "Commit".
(https://hyperledger.github.io/fabric-sdk-node/release-1.4/tutorial-sign-transaction-offline.html)
However, the signature of fabric executed by the current cactus is done by verifier in the first stage and validator in the second stage.
(https://github.com/hyperledger/cactus/blob/62824be127521cf839f434a55a7ba5cd7cee686c/packages/cactus-cmd-socketio-server/src/main/typescript/util/TransactionSigner.ts)
We change the current method so that both steps are done in validator. To do so, we move both of the code for the two-stage signature to verifier.

**Comment by outSH** [comment]
Signing logic moved to connector
