### ISSUE TITLE
ci: custom check for license being Apache-2.0

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1642]
The ODAP hermes plugin snuck in an incorrect license declaration in the package.json
file and it would be nice to avoid this in the future with better automation.

Assignees: @petermetz
Labels: P4,Tests,good-first-issue-300-advanced,good-first-issue,Hacktoberfest

**Comment by micoferdinand98** [comment]
Good day Peter, I've picked this ticket to be assigned to me, Thank you.

**Comment by petermetz** [comment]
Point of interest: tools/custom-checks/run-custom-checks.ts

**Comment by micoferdinand98** [comment]
> Point of interest:
> 
> * tools/custom-checks/run-custom-checks.ts
> * Also in the root package.json `"custom-checks": "TS_NODE_PROJECT=./tools/tsconfig.json node --trace-deprecation --experimental-modules --abort-on-uncaught-exception --loader ts-node/esm --experimental-specifier-resolution=node ./tools/custom-checks/run-custom-checks.ts",`

![image](https://user-images.githubusercontent.com/55821921/162708755-64f134d3-1289-4e5c-8892-8a859466b47e.png)

Good Day Peter, Upon investigating for proper solutions, Am I allowed to use this license checker as reference or should I create it from scratch​. ​https://github.com/bbc/apache2-license-checker & https://github.com/marketplace/actions/license-checker

**Comment by petermetz** [comment]
> > Point of interest:
> > 
> > * tools/custom-checks/run-custom-checks.ts
> > * Also in the root package.json `"custom-checks": "TS_NODE_PROJECT=./tools/tsconfig.json node --trace-deprecation --experimental-modules --abort-on-uncaught-exception --loader ts-node/esm --experimental-specifier-resolution=node ./tools/custom-checks/run-custom-checks.ts",`
> 
> ![image](https://user-images.githubusercontent.com/55821921/162708755-64f134d3-1289-4e5c-8892-8a859466b47e.png)
> 
> Good Day Peter, Upon investigating for proper solutions, Am I allowed to use this license checker as reference or should I create it from scratch​. ​https://github.com/bbc/apache2-license-checker & https://github.com/marketplace/actions/license-checker

@micoferdinand98 Sorry for the slow response. That tool checks the dependencies' licences not just our own packages so it's not suitable for this unfortunately.
