### ISSUE TITLE
feat(cactus-common): add createRuntimeErrorWithCause() & newRex()

### ISSUE THREAD

**Issue by m-courtin** [hyperledger/cacti#1702]
**Describe the bug**

In multiple places in the code within a catch block the ` .message` and ` .stack` is directly getting accessed without any checks. As possibly all things can be thrown in TypeScript / JavaScript (even undefined or null etc.) and not only Error objects. Therefore it needs to be validated first if ` .message` respective ` .stack` are existing before they are getting accessed. Furthermore a fallback should be implemented in case the thrown objects are no regular Error objects and not providing the requested properties or the stringify of the ` .stack` for example is failing due to hierarchy depth etc.

**Comment by petermetz** [comment]
@m-courtin FYI: Here is a related issue #1129 and the PR corresponding to said issue that @Leeyoungone has been working on for some time: #1384

**Comment by Leeyoungone** [comment]
@petermetz Thanks for the ping and letting me know. Do you happen to have an example of

> needs to be validated first if ` .message` respective ` .stack` are existing before they are getting accessed.

Do you happen to have any code examples that validate the `.message` and `.stack` before they are getting accessed?

**Comment by m-courtin** [comment]
@petermetz: Thank you very much for the heads-up about the PR @Leeyoungone is working on. So I will only include the basic functionality into my PR that @Leeyoungone can use it in her PR

**Comment by petermetz** [comment]
> Do you happen to have any code examples that validate the `.message` and `.stack` before they are getting accessed?

@Leeyoungone  Yup, this is it:

```typescript
if (ex instanceof Error) {
// ex has .message and .stack
}
```

**Comment by Leeyoungone** [comment]
@petermetz Ah cool cool! thank you :)
