### ISSUE TITLE
build(deps): upgrade to TS 4.4 test-plugin-ledger-connector-besu

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1747]

**Comment by arnabnandikgp** [comment]
I am new to cacti and wanted to make some beginner level contributions to the project, but all these similar issues related to 'upgrading to ts 4.4' seem to be worked upon but stalled simultaneously for some reason, is their any problem related to these issues or is everything's just ok?

**Comment by petermetz** [comment]
> I am new to cacti and wanted to make some beginner level contributions to the project, but all these similar issues related to 'upgrading to ts 4.4' seem to be worked upon but stalled simultaneously for some reason, is their any problem related to these issues or is everything's just ok?

@arnabnandikgp Hi and sorry for the very slow response!
Yeah all of these were dependent on us having some utility functions available for convenient error handling patterns. Nowadays these are available so my plan is to solve one of these bugs just as an example on how the rest could be done as well (it's relatively straightforward once you see the patterns that need applying so please stay tuned for more if you are still interested in working on one of these)

**Comment by outSH** [comment]
TS 4.9.5 is used now
