### ISSUE TITLE
ci: add container scanning to default checks

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1876]
### Description
As a maintainer I want to have automated security scans running on our containers so that I'm a tiny bit more confident that we are doing a good job of keeping our code as secure as possible.

https://github.com/Azure/container-scan

### Acceptance Criteria
1. Add a GH Action workflow that uses the container scanning action linked above
2. The scan must run through all the images that are currently being built by the CI (see all the files matching the path pattern `.github/workflows/*-publish.yaml` for a list of these)
3. If the scans return errors, then create sub-tasks for each scanning error that is of a high or critical severity security issue.
4. The check itself must be passing
5. The checks must run on every PR that builds images - if the checks take too long (e.g. hours) then we might consider only running them upon merge onto main but this is not preferred.

---

**2023-06-14 Update:**

The azure container scan [1] project has been deprecated in the meantime so we have to look for another alternative that is free, open source software that we can use for the same purpose.
[1] https://github.com/Azure/container-scan

**Comment by zondervancalvez** [comment]
Hi @petermetz, please assign this to me. Thanks.

**Comment by petermetz** [comment]
@zondervancalvez More info I discovered while doing the scans: It might be more practical to have our own workflow that runs trivy (a part of the azure container scan tool I linked in the description of the issue above).
Not saying that this is the way for sure, but it might be a more flexible option. I'll let you investigate the details of it.

**Comment by petermetz** [comment]
@zondervancalvez FYI and also a note to myself: The azure container scan project has been deprecated: https://github.com/Azure/container-scan

**Comment by zondervancalvez** [comment]
I'll continue to work on this ticket but using **Trivy container scan**. I will redo the vulnerability scan using Trivy for the _closed_ tickets that used Azure scan before.
