### ISSUE TITLE
refactor: rename *-socketio packages

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1886]
### Description

As a user of the project I want to have clarity on the distinguishing features of the packages so that scanning the list of packages in the project gives me a (slightly) better idea of what I'm dealing with.

### Acceptance Criteria
1. Come up with the distinguishing feature of said packages. (having socketio support is not one)
2. Rename the packages where `socketio` is replaced with the word that describes the difference
3. Perform the rename within the package.json files as well as in the documentation
4. Also rename the classes accordingly within the codebase.

@takeutak @izuru0

**Comment by outSH** [comment]
Plugins refactored
