### ISSUE TITLE
build(yarn): Can't add new package - "expected workspace package to exist for \"webpack-cli\""

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#1935]
**Describe the bug**

Using `yarn add <package>` on main:HEAD ends with an error. Also, some ugly warnings are printed (`warning Lockfile has incorrect entry for ...`).

**To Reproduce**

`yarn add <package>` in any cactus package (checked on more than one).

**Expected behavior**

Package should install, no warnings.

**Logs/Stack traces**

```
outsh@outsh-UbuntuCactusVM:/tmp/cactus/packages/cactus-plugin-ledger-connector-quorum$ yarn add run-time-error@1.4.0
yarn add v1.22.17
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "lodash@4.17.21". Ignoring it.
warning Lockfile has incorrect entry for "lodash@^4.17.21". Ignoring it.
warning Lockfile has incorrect entry for "lodash@4.17.19". Ignoring it.
warning Lockfile has incorrect entry for "underscore@1.12.1". Ignoring it.
warning Lockfile has incorrect entry for "glob-parent@^6.0.0". Ignoring it.
warning Lockfile has incorrect entry for "ansi-html@0.0.7". Ignoring it.
warning Lockfile has incorrect entry for "underscore@1.9.1". Ignoring it.
warning Lockfile has incorrect entry for "glob-parent@^3.1.0". Ignoring it.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "workspace-aggregator-260e8a8b-ef5d-47c3-b190-826e5364a0d5 > @hyperledger/cactus-example-carbon-accounting-frontend > @ionic-native/core@5.35.0" has incorrect peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning "workspace-aggregator-260e8a8b-ef5d-47c3-b190-826e5364a0d5 > @hyperledger/cactus-example-carbon-accounting-frontend > @ionic-native/splash-screen@5.35.0" has incorrect peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning "workspace-aggregator-260e8a8b-ef5d-47c3-b190-826e5364a0d5 > @hyperledger/cactus-example-carbon-accounting-frontend > @ionic-native/status-bar@5.35.0" has incorrect peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning "workspace-aggregator-260e8a8b-ef5d-47c3-b190-826e5364a0d5 > @hyperledger/cactus-example-carbon-accounting-frontend > @ionic/angular-toolkit@4.0.0" has unmet peer dependency "@angular-devkit/architect@^0.1200.0".
warning "workspace-aggregator-260e8a8b-ef5d-47c3-b190-826e5364a0d5 > @hyperledger/cactus-example-carbon-accounting-frontend > @ionic/angular-toolkit@4.0.0" has unmet peer dependency "@angular-devkit/schematics@^12.0.0".
error An unexpected error occurred: "expected workspace package to exist for \"webpack-cli\"".
info If you think this is a bug, please open a bug report with the information provided in "/tmp/cactus/packages/cactus-plugin-ledger-connector-quorum/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Operating system name, version, build:**
```
Linux 5.13.0-35-generic x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by outSH** [comment]
@petermetz Any insights regarding this one? I think it started to occur just after releasing of V1 (864449fb96c39e4605d5df4d51465af765b3d10f) - possibly caused by several version bumps that happened before it. Do you have any idea what may cause this problem? (it still occurs on other colleagues machines as well)

**Comment by petermetz** [comment]
> @petermetz Any insights regarding this one? I think it started to occur just after releasing of V1 ([864449f](https://github.com/hyperledger/cactus/commit/864449fb96c39e4605d5df4d51465af765b3d10f)) - possibly caused by several version bumps that happened before it. Do you have any idea what may cause this problem? (it still occurs on other colleagues machines as well)

@outSH I'm not sure either unfortunately what the root cause is (apart from yarn v1 being buggy and EOL). The long term solution is being worked on in the form of a Yarn v3 migration that is in progress as we speak. The short term one is to add the packages to the package.json file of your package manually and then running `yarn install`.

**Comment by petermetz** [comment]
@outSH Now I'm sure that it was the  buggy EoL Yarn v1 causing the issue because the upgrade to v3 fixed it (I can no longer reproduce it on the main branch).

https://github.com/hyperledger/cacti/issues/1142
