### ISSUE TITLE
feat(connector-indy): add indy plugin implementation

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1950]
# Summary

Develop a Cactus Indy connector plugin + test infrastructure (container images, container manager class, etc.) from scratch (container images only need to be created from scratch if there is no existing one available that fits the purpose). 
Include end to end test cases powered by Jest and the said testing infrastructure that prove that the connector is working as intended with a locally simulated Indy network.

You will be creating a new package in the Cactus monorepo from scratch under the `packages/cactus-plugin-ledger-connector-indy/` path.

# Acceptance Criteria

1. Indy All-In-One image is created or discovered and used as-is. If needed to create from scratch, place it under `tools/docker/indy-all-in-one/Dockerfile` which also has a README.md next to it explaining the building and running of the image and it's containers (`tools/docker/indy-all-in-one/README.md`)
1.1 Container health checks must be be operational and reliable for the image meaning that the `HEALTHCHECK` keyword needs to be used within the `Dockerfile` to define when the container has finished launching (e.g. it must only pass once the ledger is up and running, ready to accept transactions)
2. The AIO image mentioned above is published to the official GitHub Container Registry under the fully qualified image tag of `ghcr.io/hyperledger/cactus-indy-all-in-one:2022-MM-DD-$GIT_SHORT_HASH` for example `ghcr.io/hyperledger/cactus-indy-all-in-one:2021-01-08-7a055c3` (do not use the exact example tag of course)
3. A `packages/cactus-test-tooling/src/main/typescript/indy/indy-test-ledger.ts` code file is added with a `IndyTestLedger` class in it that is responsible for providing a `start()` method that takes care of launching
4. A `packages/cactus-plugin-ledger-connector-indy/src/main/typescript/plugin-ledger-connector-indy.ts` file is added with a `PluginLedgerConnectorIndy` class in it. This class uses the `indy-sdk` npm package under the hood to implement the connector's usual methods: https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md
5. The functionality of the connector is covered by the end to end tests mentioned earlier. The tests must be using the AIO image to simulate a production Indy ledger with reasonable accuracy (so not really an actual production ready deployment, but as similar as possible with minimal resource usage so that it works on an "average" developer machine).
6. Web services are implemented so that the connector's functionality can be exposed via the network when the plugin is loaded into the Cactus API server.
7. Tests are also covering (e.g. using) the generated API client class (for which you'll need to define the necessary request and response types and endpoints in a file at `packages/cactus-plugin-ledger-connector-indy/src/main/json/openapi.json` file.

# Links, Tips, Useful Information

> Most important tip: You should study the code of other - already working - connector plugins to see how they implement web services for example. A lot of the code is just boilerplate around the actual logic that translates Cactus API requests into indy-sdk calls to the Indy ledger.

1. The indy-sdk seems to have some native code (C++ compiled binaries) dependencies, so watch out for these and try to avoid having to change the default Cactus build if possible (sometimes it's not possible, but an attempt has to be made to keep it simpler rather than to complicate it further potentially needlessly)
2. Start with the connector plugin package's implementation by simply copy pasting one of the existing connectors and then find & replace the ledger name within that folder accordingly ($COPIED_LEDGER_NAME => `indy`)
3. Double check that in `packages/cactus-plugin-ledger-connector-indy/package.json` the dependency versions to other Cactus packages are up to date and that the name of the package itself is also up to date.
4. There is already some working code for Indy ledger integration, but that is written in Python which we cannot use (without additional complexity) so a Typescript based solution is still needed.

**Comment by stonechen1995** [comment]
Stone

**Comment by outSH** [comment]
@petermetz @stonechen1995 @jscode017 Are you guys working on this issue?

**Comment by petermetz** [comment]
@outSH Not me, sorry for not keeping this up to date from my part!

**Comment by jscode017** [comment]
> @outSH Not me, sorry for not keeping this up to date from my part!

Not me too, sorry for not updating my status. @petermetz can you unassign me? I can not find the self-unassigned button on my computer, thanks.

**Comment by petermetz** [comment]
> > @outSH Not me, sorry for not keeping this up to date from my part!
> 
> Not me too, sorry for not updating my status. @petermetz can you unassign me? I can not find the self-unassigned button on my computer, thanks.

@jscode017 No worries! It is currently unassigned so it's all good.

**Comment by stonechen1995** [comment]
Not me either. Thanks for notifying us. On Oct 26, 2023, at 3:15 PM, Peter Somogyvari ***@***.***> wrote:﻿


@outSH Not me, sorry for not keeping this up to date from my part!

Not me too, sorry for not updating my status. @petermetz can you unassign me? I can not find the self-unassigned button on my computer, thanks.

@jscode017 No worries! It is currently unassigned so it's all good.
