### ISSUE TITLE
docs(build): add text build steps for Linux, Mac and Windows

### ISSUE THREAD

**Issue by AbhinavMir** [hyperledger/cacti#1963]
The current [build](https://github.com/hyperledger/cactus/blob/main/BUILD.md) instructions use YouTube videos to display how to build Cactus locally. While this is great in general, but people with accessibility issues might run into problems. The videos are divided and text is small, someone with slower internet or bad eyesight for example wouldn't be able to access this. Due to lack of sound, this is completely inaccessible to the visually impaired.

I propose an Iroha-like [documentation](https://iroha.readthedocs.io/en/main/build/index.html) in addition to current documentation.

If assigned, I'm happy to make these changes ASAP. Open to views.

**Comment by petermetz** [comment]
@AbhinavMir Very much agreed and thank you so much for bringing this up! Assigning now and thank you in advance for all your contributions!

**Comment by petermetz** [comment]
@AbhinavMir Please also note that I slightly refactored the issue title which now you can copy paste into your future commit message that you'll make the changes in (we have a commit message linter so that's why this is more important than it looks at first sight)

**Comment by ashnashahgrover** [comment]
Please assign me

**Comment by jagpreetsinghsasan** [comment]
@petermetz we have assigned @ashnashahgrover for covering specifics of Cacti setup for MacOS.
Once done, we will have someone to update it for Ubuntu 22.04

**Comment by petermetz** [comment]
@jagpreetsinghsasan Nice, thank you! @ashnashahgrover Good luck and thank you as well!
