### ISSUE TITLE
feat(scorpion): ledger explorer graphical user interface

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1979]
**Is your feature request related to a problem? Please describe.**

We do not have any way to show data on ledgers.
The Hyperledger Explorer project only supports Fabric and the development has slowed so there is an opportunity for us to deliver value.

**Describe the solution you'd like**

1. A GUI package built with Angular that is called `cactus-scorpion` (the shortlist of names comes from [Top 50 Amazing Sahara Desert Animals](https://owlcation.com/stem/sahara-desert-animals), special thanks to @hartm @takeutak and @sfuji822 for being on the impromptu naming committee for this)
2. The package is compatible with `cmd-api-server` so that it can be served the same way that the `cactus-cockpit` package used to be before it got deprecated
3. In fact, the former `cactus-cockpit` package is a great starting point for the scorpion package to the point that if you look up the git history you can extract the code for it and then copy+rename it to get going the easiest possible way.
4. The application should have a sliding menu
5. One of the menu items should be named `Ledgers`
6. When the user clicks on the `Ledgers` menu item they are taken to a list of ledgers that the current running instance of the API server is connected to.
7. When clicking on any of those ledgers on the list, some metadata is displayed and a list of blocks/transactions are also rendered.
8. What the block/tx data looks/contains/formatted like will be slightly different for each ledger since each ledger has some unique characteristics to it, this is not a problem. We want to make sure that all relevant data is displayed rather than only displaying the common types of pieces of information (lowest common denominator)
9. If a ledger is not yet supported by scorpion then some graceful handling must be done on the UI in a way that is non-ambiguous. For example we could still show the ledger in the list of ledgers but then when the user clicks on it we could show a message that says "The current version of scorpion does not yet support the $LEDGER_NAME". This is preferred to just not showing a ledger in the list at all if it's not yet supported because that confuse people into thinking that they did not configure something correctly.
10. The GUI has to be responsive, work and present well on handheld devices such as phones, tablets laptops and large desktop screens (4k, 5k, etc. resolutions)
11. It would be great if there was no polling involved and instead SocketIO endpoints could be used to stream data changes for each ledger. 
12. End to end test coverage powered by [Angular's Protractor](https://protractor.angular.io/) that verify that certain block/tx data is indeed rendered on the GUI as it gets added to a ledger (the AIO containers can host the ledger and then an instance of cmd-api-server can host the GUI that protractor can run assertions against checking if the block data showed up on the GUI or not) 

**To be defined**:
1. The data to show for each ledger (e.g. what columns to show on a grid)

**Describe alternatives you've considered**

There is another school of thought where we could just make explorer tooling part of a recommended reference deployment architecture and then we don't have to maintain any of the code for such a tool. It is unclear at the time of this writing if we could achieve sufficient coverage of supported ledgers though (e.g. is there such tooling for each ledgers or are we the trailblazers here)

**Additional context**

`N/A`

**Comment by jagpreetsinghsasan** [comment]
This is interesting!

**Comment by outSH** [comment]
@petermetz Can this be closed as implemented in https://github.com/hyperledger/cacti/issues/2224, or do we have plans on implementing separate GUI? If so, what additional featured beside viewing ledger state is planned for scorpion?

**Comment by petermetz** [comment]
> @petermetz Can this be closed as implemented in #2224, or do we have plans on implementing separate GUI? If so, what additional featured beside viewing ledger state is planned for scorpion?

@outSH Works for me! Thank you for keeping up to date with these!
