### ISSUE TITLE
documentation about relationships between key components of Cactus architecture

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cacti#198]
**Is your feature request related to a problem? Please describe.**
No. But we should clarify the relationship between key components of Cactus architecture for defining interface of libraries and servers. 

**Describe the solution you'd like**
We should describe the common understanding on relationship between key components in whitepaper. Then, we can apply re-factoring on existing codes for alignment with new architecture.

**Comment by kikoncuo** [comment]
Is this considered done? can we close this issue? @sfuji822

**Comment by petermetz** [comment]
@sfuji822 +1 ^^

**Comment by petermetz** [comment]
Closing as stale for now, feel free to re-open anytime of course!
