### ISSUE TITLE
When running yarn run configure below error is shown

### ISSUE THREAD

**Issue by Helkyd** [hyperledger/cacti#1998]
**Describe the bug**

When running yarn run configure

**To Reproduce**

Git clone and installing all steps from https://github.com/hyperledger/cactus/blob/1413bbe462d29ae2ee98a3f1373fdc818eb55885/BUILD.md

**Screenshots**

![image](https://user-images.githubusercontent.com/20396898/166206533-4d684648-813c-4878-9259-ffa32dcfcd2a.png)

**Cloud provider or hardware configuration:**
Are you running the software on a dev machine or somewhere in the cloud?

**Operating system name, version, build:**

Use this command: `printf "$(uname -srm)\n$(cat /etc/os-release)\n"`
Linux 5.15.0-27-generic x86_64
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

1413bbe4

**Comment by RafaelAPB** [comment]
What is your node version?

**Comment by outSH** [comment]
Should be fixed in https://github.com/hyperledger/cacti/commit/088da9fddef794f2983802e5d4294d0849ec4a69. Closing for now, please re-open if the issue still remains on the `main` branch.
