### ISSUE TITLE
errors when build eletricity-trade example

### ISSUE THREAD

**Issue by Capn-lyz** [hyperledger/cacti#2097]
**Describe the bug**
when I execute the script ./script-build-electricity-trade.sh, it report following error:

../../node_modules/@types/ssh2/index.d.ts:39:18 - error TS2430: Interface 'Channel' incorrectly extends interface 'Duplex'.
  The types returned by 'destroy(...)' are incompatible between these types.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

39 export interface Channel extends stream.Duplex {
                    ~~~~~~~


Found 1 error.

**To Reproduce**

 execute the script ./script-build-electricity-trade.sh 

**Work Around**
I changed the interface definition of Channel in ../../node_modules/@types/ssh2/index.d.ts
from  
> destroy(): void; 

 to
  
> destroy(): this;

then it worked, but I don't know if this is the correct way

**Comment by outSH** [comment]
`electricity-trade` has been refactored since then, it should start correctly from main branch now
