### ISSUE TITLE
docs(identity): design Indy solution blueprint + add RFC

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger/cacti#21]
- [x] @hugo-borne  to share materials
- [x] From there we will circulate ideas with the community to try and confirm interest & approach
- [ ] Assuming there is sufficient community interest & buy-in, then will define roadmap scoping

Consortium Plugin - Indy: #675

**Comment by petermetz** [comment]
Ideas are presented by the whitepaper and we are presenting for the HL identity WG on June 10th to facilitate productive feedback/more ideas.

**Comment by petermetz** [comment]
@PranjayPathak @satyamgupta0103 @princekumar4812 Thank you very much for your future contribution in advance! I assigned the issue(s) to the 3 of you  as requested. Please message here/RocketChat/Mailing List if you need any help or just join one of the morning pair programming calls that we run every weekday.
