### ISSUE TITLE
Errors Staring Project on Local Machine

### ISSUE THREAD

**Issue by bobbyngwu** [hyperledger/cacti#2101]
**Describe the bug**

Hi, thanks for the wonderful project done in Cactus and all the work that has been done on this. I am new to the Blockchain space and I stumbled onto Cactus. I found it interesting and wanted to have a play. I successfully followed the steps on the [Supply Chain Example](https://github.com/hyperledger/cactus) and was able to get it all up and running. I wasn't sure what next to do and how to actually see the asset transfer though... So I decided to try other use cases.  

For 2 days now I have been trying to run the `npm run configure` task for the [discounted car trade case](https://github.com/hyperledger/cactus/blob/main/examples/discounted-cartrade/README.md#cactus-discounted-cartrade) with no luck. I have been working around a few but now stuck at `lerna run codegen`, the error I get is Task not found: "'codegen:*'". I am still troubleshooting and hope to find the solution to this.

When I remove that specific task so I can make progress given its not absolutely necessary to start the app, I encounter further errors down. I have been through the Build page severally to ensure I haven't missed. It fails to build any of the 10 projects...

**To Reproduce**

Clone the repo to a Windows 11 env and try following the steps listed in [here](https://github.com/hyperledger/cactus/blob/main/BUILD.md)

**Expected behavior**

Expects the project to build as described

**Logs/Stack traces**

Can help maintainers identify root causes

**Screenshots**
error trying to run codegen
![image](https://user-images.githubusercontent.com/10573649/175794576-aa431105-1d53-4777-a1c0-1777c753584e.png)

error I get when I skip codegen
![image](https://user-images.githubusercontent.com/10573649/175794661-05dff0a8-dfc4-4965-8fd0-4866930ba6d1.png)

**Cloud provider or hardware configuration:**
Are you running the software on a dev machine or somewhere in the cloud?

**Operating system name, version, build:**

NAME= Windows 11 Home
Version: 10.0.22000 Build 22000

For example

```sh
$ printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Linux 4.15.0-70-generic x86_64
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**
a69a9578

**Hyperledger Cactus Plugins/Connectors Used**

 - Which DLT connectors are you using (Fabric, Quorum, Corda, Besu, etc.)

**Additional context**

**Comment by jagpreetsinghsasan** [comment]
Hi there!
Can you try running the following command
`yarn run reset:node-modules`
And then try to run the `yarn run configure`

If reset:node-modules doesnt work, please remove the node_modules folder from the root of the cactus folder and try running the `yarn run configure` command again.

Let us know here if that doesnt work

**Comment by bobbyngwu** [comment]
Hi @jagpreetsinghsasan I can confirm this issue is happening on Windows. Mac builds fine. Is there something I need to explicitly do on Windows OS to get this up and running please?

**Comment by bobbyngwu** [comment]
Made some progress as this seems to be OS env related, removed the single quotes in packages.json

` "codegen": "'run-p codegen:*'"` to this  `"codegen": "run-p codegen:*"`
 
 This allowed it to execute the codegen, but then now stuck at running protoc-gen-ts with output:
 
```
 \cactus\node_modules\grpc-tools\bin\protoc.exe --plugin=protoc-gen-grpc=C:\Work\Blockchain\hyperledger\cactus\cactus\node_modules\grpc-tools\bin\grpc_node_plugin.exe --plugin=protoc-gen-ts=../../node_modules/.bin/protoc-gen-ts --ts_out=grpc_js:./src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/ --proto_path ./src/main/proto/weaver/common/protos/ ./src/main/proto/weaver/common/protos/common/*.proto ./src/main/proto/weaver/common/protos/corda/*.proto ./src/main/proto/weaver/common/protos/driver/*.proto ./src/main/proto/weaver/common/protos/networks/*.proto ./src/main/proto/weaver/common/protos/relay/*.proto
--ts_out: protoc-gen-ts: %1 is not a valid Win32 application
```

**Comment by jagpreetsinghsasan** [comment]
I have not tried it personally on the windows machine.
For windows, a containerized pre-configured environment is good.
You can refer [this](https://github.com/hyperledger/cactus/tree/main/.devcontainer) for the container way.
Let me know if this helps

**Comment by outSH** [comment]
For now Cacti is tested on linux only, ideally Ubuntu 20 / 22. Please consider use of VM, WSL or .devcontainer as suggested by Jagpreet. Please let me know / reopen if issue still occurs
