### ISSUE TITLE
fix(test-tooling): rustc container memory is not defined

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2104]
**Describe the bug**

```sh
   ok 41 All WASM build files OK
    not ok 42 ReferenceError: memory is not defined
      ---
        operator: error
        at: bound (/home/runner/work/cactus/cactus/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
        stack: |-
          /tmp/cactus-test-tooling-rustc-container-test2022530-13267-iz29ib.vbfdl/hello_world_bg.js:165
          cachedInt32Memory0 = new Int32Array(wasm.memory.buffer);
          ReferenceError: memory is not defined
              at Object.<anonymous> (/tmp/cactus-test-tooling-rustc-container-test2022530-13267-iz29ib.vbfdl/hello_world_bg.js:165:42)
              at Generator.next (<anonymous>)
              at Generator.next (<anonymous>)
              at Object.<anonymous> (/tmp/cactus-test-tooling-rustc-container-test2022530-13267-iz29ib.vbfdl/hello_world.js:1)
              at Generator.next (<anonymous>)
```

**To Reproduce**

Run `packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-bundler.test.ts`

**Expected behavior**

Passes.

**Cloud provider or hardware configuration:**

Everywhere.

**Operating system name, version, build:**

Ubuntu-20.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main`

**Comment by aldousalvarez** [comment]
Hello @jagpreetsinghsasan I would like to work on this one, Thanks

**Comment by aldousalvarez** [comment]
Upon checking we no longer have `packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-bundler.test.ts` on our repository, so I think we can now close this issue.

**Comment by petermetz** [comment]
@aldousalvarez Agreed, closing it for now. Thank you for looking into it.
