### ISSUE TITLE
feat(fabric): support tls connection to fabric nodes

### ISSUE THREAD

**Issue by izuru0** [hyperledger/cacti#2141]
**Is your feature request related to a problem? Please describe.**

fabric connector does not support tls connection towards fabric nodes

**Describe the solution you'd like**

enable fabric connector to use tls connection towards fabric nodes

**Comment by aruns05** [comment]
@izuru0 Is this still an issue?

**Comment by outSH** [comment]
Fabric connector can connect to SSL nodes now (example - https://github.com/hyperledger/cacti/blob/main/examples/cactus-example-discounted-asset-trade/fabric-connector.ts#L77)
