### ISSUE TITLE
fix(connector-iroha) : Drop array based request params

### ISSUE THREAD

**Issue by yashrajdesai** [hyperledger/cacti#2151]
**Is your feature request related to a problem? Please describe.**
The array-based approach is inflexible because if the order of params is changed it wouldn't work.

**Describe the solution you'd like**
To fix this, a request object is passed containing all the parameters and validated against the request structure schema for all commands and queries of Iroha. This issue is fixed in #2148 but the old array-based params are still kept for backward compatibility. The array-based approach can be dropped with the release of 2.0.

**Comment by aruns05** [comment]
@yashrajdesai  Is this issue sorted out ?

**Comment by outSH** [comment]
@yashrajdesai We're accepting changes to 2.0 now, do you want to submit a PR that removes the array-based args? Or do you want to give this task to someone else?

**Comment by petermetz** [comment]
@outSH @yashrajdesai Given that Iroha v1 is no longer LTS (or maybe close to it, I can't remember the exact details) I think it's OK for us to down-prioritize this and close the issue for now. If it was for the  v2 connector then it would be a different story of course.

Of course it can be reopened anytime if we decide that.
