### ISSUE TITLE
Separate TLS from servers

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cacti#220]
**Is your feature request related to a problem? Please describe.**
Using nodeJS's integrated TLS stack is not good practice in performance and in consideration of docker environment.

**Describe the solution you'd like**
We can provide nginx frontend server for testing purpose and removing integrated TLS stack.

**Comment by petermetz** [comment]
> Using nodeJS's integrated TLS stack is not good practice in performance

Question: What is the specific production deployment scenario where you see that the optional TLS/mTLS support's mere presence would cause a performance degradation of any kind? 

> We can provide nginx frontend server for testing purpose and removing integrated TLS stack.

This is true already. You turn off the TLS/mTLS in the NodeJS process via the configuration flag and then do TLS at any other point in your infrastructure where you prefer to do so.

**Comment by petermetz** [comment]
Closing this as stale for now, feel free to re-open anytime of course!
