### ISSUE TITLE
chore(tools): script to bump openapi spec dependency versions

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2206]
### Description
As a release manager I want to have a simple and automated way of upgrading open API spec dependencies when I push a release so that everything is kept more up to date as we go along which leads to issues being detected faster/earlier.

Currently we have URL references to tagged versions of the spec files such as this one:
https://raw.githubusercontent.com/hyperledger/cactus/v0.8.0/packages/cactus-core-api/src/main/json/openapi.json#/components/schemas/JWSGeneral

The issue is that we are already on v1.1.2 at the time of this writing but there are still references to relatively old (especially pre-v1.0.0) spec files which runs the risk of us having bugs or breaking API changes added later by accident.

Manually looking and updating these references are tedious but since the spec files are valid JSON documents, we can certainly have a script that goes looking for `**/openapi.json` and replaces all the references with the latest available git tag.

Note: Tagging a release on the upstream is the very last step of issuing a release so we cannot change these references atomically as part of the release process (yet) but having the script doing the upgrade (even if that has to happen post-release in a separate PR) is a step in the right direction!

### Acceptance Criteria
1. Create a script in the tools directory written in Typescript that when executed: 1) determines the latest `v*` git tag on `main/upstream` and then finds and lists all the open API spec references. Finally it updates them.
2. It is important to print to stdout a complete and easily readable list of all the files that are being found and all the references for each file that as going to be updated.
3. Also make sure to include in the final log output the total number of open API spec files found AND also separately count the total count of references (since each file can have any number of references in it)

**Comment by aldousalvarez** [comment]
Hello @petermetz I would like to take this. Can you assign me on this one? Thanks!

**Comment by petermetz** [comment]
> Hello @petermetz I would like to take this. Can you assign me on this one? Thanks!

@aldousalvarez You got it, thank you!
