### ISSUE TITLE
fix(connector-socketio): use common package convention

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#2216]
**Describe the bug**

All packages should follow the same conventions to avoid problems in the future. Our socketio connector should be fixed to achieve that. Use common `package.json` and `tsconfig.json`

@petermetz comments:
> I recommend keeping the conventions of the other packages when it comes to declaring the paths & configuring the compiler (tsconfig.json file). That will avoid a big chunk of the issues like when some packages do not get published due to strange bugs: https://github.com/hyperledger/cactus/issues/2069 or other kinds of automation scripts failing if they make assumptions that some of these paths are uniform everywhere. If there is a specific reason for not going uniform with the package configuration properties then that's a different question of course but if it's all the same to you then I'd highly recommend changing it to match the rest of the packages.

> ... in general every single property in the package.json file that does not have a specific reason (like contributor list or package name/description) to be different should be the same, uniform configuration (same for tsconfig.json files).

**Comment by rwat17** [comment]
@petermetz Can i take this one?

**Comment by petermetz** [comment]
> @petermetz Can i take this one?

@rwat17 All yours, thank you very much in advance!
