### ISSUE TITLE
feat(openapi): upgrade generator to 6.x

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2217]
**Is your feature request related to a problem? Please describe.**
During the time of creation of this issue, the openapi-generator in use is `5.2.1`. Upgrading to next major version `6.x` brings in breaking changes to the existing generated codes.
Currently the openapi generated codes are present in the following packages
(can be listed using `find ./ -iwholename "./**/src/main/json/openapi.json"` )

```
./extensions/cactus-plugin-htlc-coordinator-besu/src/main/json/openapi.json
./extensions/cactus-plugin-object-store-ipfs/src/main/json/openapi.json
./examples/cactus-example-supply-chain-business-logic-plugin/src/main/json/openapi.json
./examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/json/openapi.json
./packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
./packages/cactus-plugin-keychain-google-sm/src/main/json/openapi.json
./packages/cactus-plugin-keychain-aws-sm/src/main/json/openapi.json
./packages/cactus-plugin-keychain-azure-kv/src/main/json/openapi.json
./packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
./packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
./packages/cactus-plugin-keychain-memory/src/main/json/openapi.json
./packages/cactus-plugin-ledger-connector-xdai/src/main/json/openapi.json
./packages/cactus-plugin-keychain-vault/src/main/json/openapi.json
./packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
./packages/cactus-core-api/src/main/json/openapi.json
./packages/cactus-plugin-htlc-eth-besu-erc20/src/main/json/openapi.json
./packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
./packages/cactus-cmd-api-server/src/main/json/openapi.json
./packages/cactus-plugin-keychain-memory-wasm/src/main/json/openapi.json
./packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
./packages/cactus-plugin-odap-hermes/src/main/json/openapi.json
./packages/cactus-plugin-odap-hermes/dist/lib/src/main/json/openapi.json
./packages/cactus-plugin-htlc-eth-besu/src/main/json/openapi.json
```

As there are lot of dependent packages and the impact of conflicts is not estimated at the time of creation of this epic, it can be gradually complete with both the openapi-generator versions `5.2.1` and `6.x`. But the closure of this epic shall only reflect the `6.x` version under all the packages.

This is a high priority issue, as completion of this will not only improve the generated code (and might fix issues related with `oneOf`, `anyOf`.. etc etc with other languages like kotlin), but will also reduce the regular dependabot upgades related to the generated code libraries.
Completion of this epic shall be targeted prior to our `2.0.0` release so that we can make that breaking change in our own code with the publishing of our own `v2.0.0`

**Describe the solution you'd like**
1. Updating the specified package code to make it work with the newly generated code
2. Testing of the respective test cases
2. The CI pipelines should pass

**Comment by jagpreetsinghsasan** [comment]
@petermetz I am unable to add #2298 and #2299 issues to this epic (the zenhub missing permission).
The `Add issues to this epic` is not accessible by me here (the bottom most button in the referenced screenshot)
![image](https://user-images.githubusercontent.com/56861721/220851688-b92e4ba0-16b7-4af1-b5e1-d2158ac72fff.png)

**Comment by petermetz** [comment]
@jagpreetsinghsasan Sorry for the slow response! In the meantime ZenHub went paid-only (no more free tier that we can use that I could find) so now we are on GitHub projects to track the v2 release progress: https://github.com/orgs/hyperledger/projects/27 (let me know if you have any permission issues there)

On the topic of the work for this issue: This got fixed in the meantime by https://github.com/hyperledger/cacti/pull/2633
