### ISSUE TITLE
spike(openapi): impact analysis of the upgrade

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2220]
**Is your feature request related to a problem? Please describe.**
This spike is in reference to the issue #2217 
Impact analysis of the openapi-generator upgrade from `5.x` to `6.x` is required to answer the question - `Can we mass migrate the plugins or do we really need 20+ issues to address each package independently for the upgrade?`

**Describe the outcome of this spike**
1. Compile a list of affected packages (e.g the ones that do break when we go to `6.x`)
2. Compile a list of the specific types of breakages that happen and how easy it is to deal with them (e.g. some of them will be just a quick syntax change while others might require us to re-think the whole data model that we are representing)
3. Identify which issues from 1) and 2) are being fixed upstream (in the generator - if they are caused by bugs in v6) versus how many of them are "it is what it is" type of situations where we have to adapt our specs accordingly.
4. Identify which breakages could we fix ourselves by submitting patches to the v6 generator (it might be that we just need to add some missing things to the generator, I have no idea)

Based on the above 4 points of the impact analysis, required issues within the epic #2217 needs to be created
Thanks @petermetz for providing the workflow outline to complete this spike

**Comment by jagpreetsinghsasan** [comment]
@petermetz I have done this spike and have created 2-phase approach to address the upgrade.
#2217 is the epic, and #2298, #2299 are the 2 GH issues within that epic (not able to add them to the epic myself due to zenhub permission issues)

**Comment by petermetz** [comment]
@jagpreetsinghsasan Thank you very much for the work on this!
