### ISSUE TITLE
build(yarn): migrate to CorePack

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2238]
### Description
As a contributor I want to have the easiest build tooling available so that I'm less bogged down with dev tooling and more focused on valuable contributions of mine.

https://yarnpkg.com/getting-started/install

Install Corepack

The preferred way to manage Yarn is through [Corepack](https://nodejs.org/dist/latest/docs/api/corepack.html), a new binary shipped with all Node.js releases starting from 16.10. It acts as an intermediary between you and Yarn, and lets you use different package manager versions across multiple projects without having to check-in the Yarn binary anymore.
Node.js >=16.10

Corepack is included by default with all Node.js installs, but is currently opt-in. To enable it, run the following command:

```
$ corepack enable
```

### Acceptance Criteria
1. Our documentation and scripts are updated so that CorePack is used

**Comment by charellesandig** [comment]
Hi @petermetz, I would like to work on this ticket, thank you.
