### ISSUE TITLE
build(deps): upgrade web3 project-wide to v1.6.1

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2332]
### Description

There is already a pull request [1] (#2271) out there - sent by the robots - to force the upgrading of the `cookiejar` dependency via the lock file, but we would like to make sure that the parent dependencies of `cookiejar` are also upgraded and the way to get that done is to upgrade web3 within the project. 

This will make sure that the lockfile getting reset does not re-introduce the vulnerability that is being fixed by #2271.

![Screenshot from 2023-03-20 15-31-50](https://user-images.githubusercontent.com/1583231/226495884-6bfd1643-81c4-47ce-8a30-22f6f1a45c9f.png)

![Screenshot from 2023-03-20 15-23-50](https://user-images.githubusercontent.com/1583231/226495887-6aeb37df-a201-4700-ad68-27ac30a58600.png)

[1]: https://github.com/hyperledger/cacti/pull/2271

### Acceptance Criteria
1. Changes are limited to the dependency upgrades and nothing more.

**Comment by micoferdinand98** [comment]
@petermetz Hello Peter I'll be taking this ticket. Thank you.
