### ISSUE TITLE
ci(custom-checks): fix broken package.json sort verification

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2356]
### Description
As a maintainer I want to have an automated CI job (that actually works) that checks for package.json files being sorted so that I don't have to manually be on the lookout for non-sorted dependencies and the like.

Previous attempt at making this happen: https://github.com/hyperledger/cacti/issues/1341

A related discussion I had with @outSH about this: https://github.com/hyperledger/cacti/pull/2310#discussion_r1152057132

### Acceptance Criteria
1. The custom checks fail in the CI if any package.json files are found which were previously unsorted.
2. When the custom checks are executed locally, the ensure sort check can still be used to perform the sorting so that contributors

**Comment by rwat17** [comment]
@petermetz 
I have done some work towards this issue. Please review if it suits your requirements.

Found error in usage of sort-package in scripts introduced in this issue https://github.com/hyperledger/cacti/issues/1341.
Module API accepts only JSON objects https://www.npmjs.com/package/sort-package-json. But here https://github.com/hyperledger/cacti/blob/3e6d908cb4cf732ef057a30df3e8267381f3f806/tools/custom-checks/check-package-json-sort.ts#L51 only paths to the files are passed.

I did simple CI action to check if package.json files in /examples and /packages are sorted. If not, it prints short script to run in cactus root folder to sort remaining packages.

**Comment by petermetz** [comment]
> @petermetz I have done some work towards this issue. Please review if it suits your requirements.
> 
> Found error in usage of sort-package in scripts introduced in this issue #1341. Module API accepts only JSON objects https://www.npmjs.com/package/sort-package-json. But here
> 
> https://github.com/hyperledger/cacti/blob/3e6d908cb4cf732ef057a30df3e8267381f3f806/tools/custom-checks/check-package-json-sort.ts#L51

@rwat17 Thank you very much!

My preferred way would be to solve it via the existing NodeJS script instead of going down a level to writing shell because of these questions that popped into my head:

Questions: 
1. Did you verify the shell script to also be working for Mac users? We've had lots of bugs in the past where tiny little implementation details made things broken on either Linux or mac and also Windows back when our build was still supported on it (and we should - in my opinion - eventually get the build working again on Windows/PowerShell as well)
2. Can the shell script be changed/extended (relatively easily) later to pull package path patterns (globs) from the root folder's lerna.json file? This is a future change we'll need to change because of the cactus -> cacti rename all of these hardcoded globs will start failing soon. I'm thinking maybe with some clever `jq` magic it can be made so that the shell script parses the lerna.json file for the globs and then iterates through them but I'm a little worried that by that point the shell code will be hard to read/understand for beginners.
3. Is there an easy way to plug in the shell script into the existing set of "custom checks" that get executed when we run `yarn run custom-checks`? The only way I can think of is that the custom-checks script starts spawning other processes to run the shell script, not necessarily bad but it does increase complexity 'coz now we have to write logic to parse and interpret the stdout/stderr of that process in addition to just running the check itself.

If all of these are OK in your opinion then I'd be fine with the shell script instead of the NodeJS script, just let me know your thoughts!
