### ISSUE TITLE
test(connector-corda): fix flaky watchBlocksAsyncV1 corda v4.8

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2376]
**Describe the bug**

The test in the file below is flaky:
`packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/monitor-transactions-v4.8.test.ts`

Probably related to or the same race condition that was causing #1995 

**To Reproduce**

Run the CI enough times that it eventually fails instead of succeeding.

**Expected behavior**

Test passes consistently in all environments.

**Logs/Stack traces**

[2023-04-06T21-20-36_connector-corda-monitor-transactions-v4.8-crash.log](https://github.com/hyperledger/cacti/files/11175238/2023-04-06T21-20-36_connector-corda-monitor-transactions-v4.8-crash.log)

**Cloud provider or hardware configuration:**

GitHub/BuildJet

**Operating system name, version, build:**

Ubuntu-20.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main`

**Hyperledger Cactus Plugins/Connectors Used**

Corda

cc: @outSH

**Comment by aldousalvarez** [comment]
Hello @petermetz Can you assign me on this one? I would like to work on this. Thank you

**Comment by aldousalvarez** [comment]
Hello @petermetz I cannot seem to replicate the issue. Because I tried to [run the CI](https://github.com/aldousalvarez/cactus/actions/runs/5739957159/job/15771075054?pr=4) 10 times on my fork and I still got this test file passing:

**packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/monitor-transactions-v4.8.test.ts**

![image](https://github.com/hyperledger/cacti/assets/89574062/11aa76a5-5fcb-454b-9842-1738dd1f5ae6)

**Comment by petermetz** [comment]
@aldousalvarez Gotcha, let's just leave this one closed for now and if the issue happens again we can re-open. In the meantime please book in the time you've spent on the testing/verification on your personal fork. If you don't yet have permission to edit the project estimates you can ask @jagpreetsinghsasan to do the updates. In the meantime I'm working on adding everyone to the HL GH org so permissions are coming soon.

**Comment by aldousalvarez** [comment]
@petermetz Got it. Thanks for the update. will update the time spent on the testing and verification.
