### ISSUE TITLE
docs(examples): upgrade Angular to v14

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2377]
### Description

We need to do the upgrades step by step so this is just a milestone on the way to upgrading to v15.

### Acceptance Criteria
1. `yarn build:dev` passes

**Comment by PiyushSharma99** [comment]
Hi @petermetz, I am working on it

**Comment by petermetz** [comment]
@PiyushSharma99 I haven't seen a pull request about it yet so I'll take over because this is getting a bit urgent to finish.
If you happen to have the diff ready to go or close to it just let me know and I'm still happy to assign it!
