### ISSUE TITLE
test(weaver): fix flaky .github/workflows/test_weaver-asset-transfer.yml

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2383]
### Description

The test in `.github/workflows/test_weaver-asset-transfer.yml` is flaky sometimes, e.g. it fails or succeeds randomly (succeeds most of the time)

[2023-04-07T18-27-47_test_weaver-asset-transfer_yml_ci_crash.log](https://github.com/hyperledger/cacti/files/11183607/2023-04-07T18-27-47_test_weaver-asset-transfer_yml_ci_crash.log)

### Acceptance Criteria
1. Test is updated so that it passes consistently

cc: @VRamakrishna @sandeepnRES

**Comment by ameya-deshmukh** [comment]
@petermetz can I take this issue up? Would love to start off with this as my first contribution to Cacti!

**Comment by sandeepnRES** [comment]
Hi @petermetz can you monitor this again? I think PR #2384 might have fixed this.

**Comment by sandeepnRES** [comment]
Closing this as it seems this is resolved (from looking at runs in recent PRs)
