### ISSUE TITLE
build fails on codegen (macOS)

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cacti#2396]
**Describe the bug**

Does not build with yarn run configure, appears to be Weaver-related.

**To Reproduce**

Install dependencies on BUILD.md. Run "yarn run configure".

**Logs/Stack traces**
https://gist.github.com/RafaelAPB/8b475d87741ff08080966dc6aa431896

**Operating system name, version, build:**
Darwin 22.3.0 arm64

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**
latest: 89d5102496adfe98a542a373e805dc38ecb8f269

**Comment by petermetz** [comment]
@RafaelAPB Please try to wipe all node_modules folders with `yarn run reset:node-modules` and then run the configure script all over again. This looks like one of those issues where yarn randomly messes up the binary symlinks across packages (I'm thinking there's a race-condition in there somewhere)

**Comment by outSH** [comment]
@RafaelAPB Did peters advice help with the issue?
