### ISSUE TITLE
ci(test-tooling): fix CI job failing due to with wasm-pack

### ISSUE THREAD

**Issue by sandeepnRES** [hyperledger/cacti#2407]
**Describe the bug**

`cactus-test-tooling` job which is marked as required for merge to main is consistently failing. On asking @jagpreetsinghsasan, he said this has something to do with `wasm-pack` not able to generate the nodejs files

**To Reproduce**

It is always reproducible, and can be checked on any open PR.

**Expected behavior**

Should succeed.

**Logs/Stack traces**

Here are the logs: 
[logs.txt](https://github.com/hyperledger/cacti/files/11346580/logs.txt)

**Comment by petermetz** [comment]
> Hi @petermetz, please assign this to me.

@adrianbatuto Done, thank you very much!
