### ISSUE TITLE
fix(tessera): updated tessera version error in quorum-all-in-one

### ISSUE THREAD

**Issue by ruzell22** [hyperledger/cacti#2411]
**Describe the bug**

Tessera version is updated in #2240 in the dockerfile of quorum-all-in-one to fix the vulnerabilities. However,  after the update, when running the docker image of quorum-all-in-one, tessera is having an issue. Versions lower than 21.1.7 works with the older version that is being used which is 21.1.1. The tessera was updated to 22.1.7 which has drastic changes which will be needed to be updated on our end as well in order for tessera to work for quorum-all-in-one.

**To Reproduce**

[process]
DOCKER_BUILDKIT=1 docker build ./tools/docker/quorum-all-in-one/ -t qaio
docker run --rm qaio

[error]
No such file or directory.

**Expected behavior**

Tessera will run when quorum-all-in-one docker image is ran. Quorum-all-in-one will run successfully as well.

**Additional context**

Related to #2240 (merged) and #2274 (fixed but on hold for tessera update)

**Comment by ruzell22** [comment]
Hello @petermetz , can you assign to this me? Thank you.

**Comment by petermetz** [comment]
> Hello @petermetz , can you assign to this me? Thank you.

@ruzell22 Done, thank you!
