### ISSUE TITLE
build(plugin-ledger-connector-ubiquity): stop using GitHub URL as client version

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2544]
We need to get rid of this dependency declaration that depends on a GitHub URL:
`"@ubiquity/ubiquity-ts-client-modified": "https://github.com/RafaelAPB/ubiquity-ts-client-mirror.git",`
because it is technical debt and a security concern at the same time.

The package in question: `packages/cactus-plugin-ledger-connector-ubiquity/package.json``
Gitlab repo: https://gitlab.com/Blockdaemon/ubiquity/ubiquity-ts-client/-/releases

- Plan A: Have the maintainers of this package publish an up to date & working
version to npmjs.com so that we can use it from there.
- Plan B: If they publish it to an alternative registry that's fine too we just
need to create the mapping for the scope (as long as they do have an org scope)
- Plan C: Their website appears to have a much newer version of the OpenAPI specification
for their APIs (v3.0.0). As a plan C we could even just generate our own client
and use that as part of the connector. This is not desired because then we would
have to maintain code that we don't really control (we don't write the specs
nor we develop the back-end APIs that they must comply with) but as a last 
resort it is an acceptable solutin if all else had failed.

OpenAPI specs: https://ubiquity.docs.blockdaemon.com/

cc: @RafaelAPB

**Comment by RafaelAPB** [comment]
I'll do this @petermetz

**Comment by petermetz** [comment]
@RafaelAPB Yay, thank you!

**Comment by aldousalvarez** [comment]
Hello. I would like to work on this one thank you

**Comment by petermetz** [comment]
@aldousalvarez Let's check in with @RafaelAPB about whether he's still working on it or would he be okay with passing it off?

**Comment by aldousalvarez** [comment]
Sure, it's okay @petermetz Thanks for the update

**Comment by RafaelAPB** [comment]
Folks, I'm still trying to go for plan A.

**Comment by RafaelAPB** [comment]
We are working on this, but do not have a clear timeline for it. Let us keep track of the issue here.

**Comment by petermetz** [comment]
@RafaelAPB Understood, thank you for the update and the help of course!

**Comment by RafaelAPB** [comment]
@petermetz if this is not corrected in two weeks (by 8th November), please feel free to remove this package. I will try my best.

**Comment by petermetz** [comment]
> @petermetz if this is not corrected in two weeks (by 8th November), please feel free to remove this package. I will try my best.

@RafaelAPB Sorry, I forgot that we had this issue open and submitted a PR with something that takes care of it (as best as I could verify it without an API token)

See the `ubiquity-ts-client-renovated` package I self-published on npm as a quick workaround:  https://www.npmjs.com/package/ubiquity-ts-client-renovated

(I also submitted the changes of that package as a PR to your repo so that we can upstream it).

TLDR: If you are OK with what I did in my PR(s): https://github.com/hyperledger/cacti/pull/2830/files
then this is no longer an urgent issue because my PR addresses it at least with a less temporary band-aid if not a proper permanent solution.

Let me know your thoughts!

**Comment by RafaelAPB** [comment]
@petermetz yep, im ok with that! thanks

**Comment by petermetz** [comment]
> @petermetz yep, im ok with that! thanks

@RafaelAPB Awesome, thank you too! In that case the urgency is now low on this, as-in, longer term it would still be optimal to have a package maintained by you and/or the original authors of that package, but the immediate technical concern related to critical and high severity vulnerabilities and direct URL installation are gone so no rush on the rest of it!
