### ISSUE TITLE
fix(plugin-odap-hermes): fix duplicate enum values of OdapMessageType

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2553]
### Description

Specifically this value `CommitFinalResponse = "urn:ietf:odap:msgtype:commit-ack-msg",` should be
`urn:ietf:odap:msgtype:commit-final-ack-msg` as per the [IETF draft's section  8.4](https://datatracker.ietf.org/doc/html/draft-hargreaves-odap-03#section-8.4)

![Screenshot from 2023-07-16 13-29-01](https://github.com/hyperledger/cacti/assets/1583231/c1a09ba3-2478-48b7-ac5f-6ad71a5e78db)

https://datatracker.ietf.org/doc/html/draft-hargreaves-odap-03#section-8.4

cc: @RafaelAPB @AndreAugusto11

**Comment by AndreAugusto11** [comment]
Thank you @petermetz!
