### ISSUE TITLE
build(tools): fix tooling globs where cactus is hardcoded

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2576]
## Summary

A few of the checks we have that are linting manifest files for example are
hardcoding glob patterns with `cactus` in them to find the files they need to 
parse but this won't work because now we started addnig new packages with 
`cacti` in them as well.

Ultimately the best solution is to keep the lerna/yarn workspace globs as the
single source of truth on what paths we must check when doing these tasks.

`tools/custom-checks/run-custom-checks.ts`

`tools/custom-checks/check-sibling-dep-version-consistency.ts`

`tools/custom-checks/check-package-json-sort.ts`

**Comment by adrianbatuto** [comment]
Hi @petermetz, please assign this to me.
