### ISSUE TITLE
build(setup): remove install-yarn and document new yarn setup

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#2582]
**Describe the bug**

After running `npm run install-yarn` error is thrown:

```
vagrant@CactusDevVM:~/tmp/cacti$ npm run install-yarn

> install-yarn
> npm install --global yarn@3.6.0

npm ERR! code ETARGET
npm ERR! notarget No matching version found for yarn@3.6.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2023-07-25T12_26_15_488Z-debug-0.log
```

**Expected behavior**

I think setup of yarn 3.X changed and this script should be removed. We should document somewhere how to enable corepack or at least add link to https://yarnpkg.com/getting-started/install

Everything else seem to be working very well, thank you for upgrading yarn @petermetz!

**Comment by petermetz** [comment]
@outSH Agreed on all of that, thank you for reporting the bug! I'll get on it right now!
