### ISSUE TITLE
chore(github): shorten ci.yaml workflow and job names

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2624]
### Description
As a maintainer I want to see which jobs are executing so that I'm having a better developer experience while contributing to the project which will make me happier and more productive in general while working on the project.

The screenshot below demonstrates the problem very well. The job names are getting cropped by GitHub's UI and are indistinguishable from each other.

![image](https://github.com/hyperledger/cacti/assets/1583231/86334ee7-ba93-49f1-8b81-6498a5868a7b)

### Acceptance Criteria
1. Each job has it's name shortened but still unique so that we can definitively identify the jobs despite the shorter names.

cc: @jagpreetsinghsasan Because he has a big PR pending with a big refactor where the job names are also relevant (the dynamic diff analysis PR)

**Comment by jagpreetsinghsasan** [comment]
True that. We can remove `cactus-plugin-*-` from each of the names and still have some way of automatically picking up names from the reduced naming schema.

**Comment by Dev-Destructor** [comment]
Hii, since I am working on #2639
I will also shorten their names.

**Comment by zondervancalvez** [comment]
Please assign this to me @jagpreetsinghsasan
