### ISSUE TITLE
spike: understand simple-asset-transfer example

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2655]
### Description
As a developer I want to explore the code and understand the simple asset transfer use-case.
This will help me in estimating and thus completing #334 

### Acceptance Criteria
1. Should be able to estimate #334

**Comment by jagpreetsinghsasan** [comment]
@ruzell22

**Comment by ruzell22** [comment]
Commenting here so this ticket can be assigned to me. Thank you.

**Comment by aldousalvarez** [comment]
@jagpreetsinghsasan Can you assign me on this one as well. Thank you

**Comment by jagpreetsinghsasan** [comment]
Based on this spike learning, I will create one more spike where @ruzell22 can look into the connectors and how they interact with the smartcontracts.
The initial acceptance criteria was to estimate the main task via this spike but upon completion of the spike, the need to understand connector interaction with the ledgers is also seen and thus the need for another spike story as a subsequent action to this one. The acceptance criteria will get carried forward in the new spike I will create and will tag the same here for reference.
