### ISSUE TITLE
style(api-client): fix Unexpected any linter warnings in extendWith<T>

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2675]
### Description

![image](https://github.com/hyperledger/cacti/assets/1583231/ee07b8c9-3d7a-40df-80ae-f09017aee16c)

**Comment by petermetz** [comment]
Pro tip: Use `Record<string, unknown>` as the type for these variables insted of `any`.

**Comment by bmvd70** [comment]
I'd like to fix this issue

**Comment by petermetz** [comment]
@bmvd70 Nice, thank you! Assigned it just now.
