### ISSUE TITLE
style(cmd-api-server): fix Unexpected any linter W in getHelpText()

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2678]
### Description

![image](https://github.com/hyperledger/cacti/assets/1583231/6be954ae-7a24-4c0f-87f1-b8c028009115)

**Comment by bmvd70** [comment]
FYI: further down in the same file, there is another linter any warning. 
But since im new, i am not sure if i am allowed to expand the current issue, or if this negatively impacts the cleanliness of the repo.

**Comment by petermetz** [comment]
> FYI: further down in the same file, there is another linter any warning. But since im new, i am not sure if i am allowed to expand the current issue, or if this negatively impacts the cleanliness of the repo.

@bmvd70 For now let's just keep the PRs focused in terms of the issue scope. If you want to do more linter warning fixes, just let me know, we have hundreds so there's plenty to go around! 

Feel free to open PRs with more fixes like these if you feel like it, just make sure to have them relatively small & easy to review (50 LOC or less is ideal but it heavily depends on the fix being done of course)

**Comment by bmvd70** [comment]
Will do, thank you for the feedback!
