### ISSUE TITLE
feat(plugin-ledger-connector-sawtooth): add Sawtooth support

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#268]
**Is your feature request related to a problem? Please describe.**

No problem, just want us to add Sawtooth because it's also a DLT in the greenhouse and would be really nice to cover as many of those as possible.

**Describe the solution you'd like**

Nothing special, just the same run of the mill ledger connector that we already have for some of the other ledgers. It's okay to have it with the absolute simplest operations supported only, we can always grow it later on. The point is, I want us to start somewhere ;-)

cc: @takeutak @jonathan-m-hamilton @sfuji822

**Comment by outSH** [comment]
Closed by https://github.com/hyperledger/cacti/pull/2825
