### ISSUE TITLE
spike: understand connector interaction with asset-transfer 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2688]
### Description
As a developer, I want to understand connector interaction with asset-transfer to be able to switch to the new architecture for the same.

### Acceptance Criteria
1. Should be able to estimate #334

**Comment by ruzell22** [comment]
I would like to work on this one, thank you.

**Comment by ruzell22** [comment]
I have logged the steps from the old code for simple asset transfer, from setting up the ledgers until the ledger B creating a copy of the exported asset. I have noticed that there are factors that needs understanding further or looking for alternatives for the current version of Cacti such as the Federation validator that is needed to perform the Blockchain action and signature validation.

Here are the things that will need looking further into:
- Federation/overlay network of validators for each ledger
- Fetch all validators’ public keys from each ledger
- Add foreign validator (the other ledger to a specific ledger’s smart contract)
- Do the 5 steps for simple asset transfer (create asset, lock asset, ask for signature, verify signature, create a copy)
