### ISSUE TITLE
style(eslint): bulk auto-fixable issues resolved project-wide - 2023-09-20

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2710]
### Description

`yarn lint` produces a huge diff of auto-fixes that are not currently applied (committed to git).

Scope of this task: apply the fixes. 

### Acceptance Criteria
1. Do not apply any manual changes. Strictly only the changes that were done by the linter.

**Comment by Yogesh01000100** [comment]
I'd like to take on this task and apply the fixes as per the acceptance criteria. I'll ensure that no manual changes are made and strictly apply only the changes generated by the linter.
let me know if you're okay with assigning me working on this, and if you have any specific instructions or preferences regarding this task.

**Comment by petermetz** [comment]
> I'd like to take on this task and apply the fixes as per the acceptance criteria. I'll ensure that no manual changes are made and strictly apply only the changes generated by the linter. let me know if you're okay with assigning me working on this, and if you have any specific instructions or preferences regarding this task.

@Yogesh01000100 There's already a PR open for this one: https://github.com/hyperledger/cacti/pull/2713
