### ISSUE TITLE
 Issue: CBDC example - Running the Example Application Locally

### ISSUE THREAD

**Issue by Anusha-Padmanabhan** [hyperledger/cacti#2747]
The escrow button is not enabled after minting and token balance is also not reflecting in the screen.
Attaching the screenshot  after minting.
<img width="366" alt="token_reflection" src="https://github.com/hyperledger/cacti/assets/119853495/56005139-a810-4050-99e9-48ce50c4cf26">

I believe, once after minting escrow and transfer buttons should get enabled and minted token balance also should be visible in the screen.

_Originally posted by @Anusha-Padmanabhan in https://github.com/hyperledger/cacti/issues/2739#issuecomment-1748209487_

**Comment by Anusha-Padmanabhan** [comment]
Since I am not a collaborator, I am unable to reopen the existing issue https://github.com/hyperledger/cacti/issues/2739 , therefore opened a new one @petermetz

**Comment by petermetz** [comment]
Duplicate of #2739
