### ISSUE TITLE
fix(plugin-htlc-coordinator-besu): missing HSTS Header

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2763]
## Description
Static source code assessment has picked up a potential vulnerability regarding undefined HSTS header. The potential fix is to include the same following the recommended remediation

## The report from which the above information was summarized
Risk Rating: Medium
Category: Security Misconfiguration

### Description
The web-application does not define an HSTS header, leaving it vulnerable to attack.

### Impact
Failure to set an HSTS header and provide it with a reasonable "max-age" value of at least one year may leave users vulnerable to Man-in-the-Middle attacks

### Remediation Recommendation
• Set the HSTS header either explicitly within application code or using webserver configurations. 
• Ensure the "max-age" value for HSTS headers is set to 31536000 to ensure HSTS is strictly enforced for at least one year. 
• Include the "includeSubDomains" to maximize HSTS coverage, and ensure HSTS is enforced on all sub-domains under the current domain.
• Note that this may prevent secure browser access to any sub-domains that utilize HTTP; however, use of HTTP is very severe and highly discouraged, even for websites that do not contain any sensitive information, as their contents can still be tampered via Man-in-the-Middle attacks to phish users under the HTTP domain.
• Once HSTS has been enforced, submit the web-application's address to an HSTS preload list - this will ensure that, even if a client is accessing the web-application for the first time (implying HSTS has not yet been set by the web-application), a browser that respects the HSTS preload list would still treat the web-application as if it had already issued an HSTS header. Note that this requires the server to have a trusted SSL certificate and issue an HSTS header with a maxAge of 1 year (31536000).

### Affected files (path - line number)

extensions/cactus-plugin-htlc-coordinator-besu/src/main/typescript/web-services/counterparty-htlc-endpoint.ts - 103

## Snapshot of the sourcecode at the time of scan
<img width="657" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/d22e6481-c4a6-48b9-b0fc-bb4b01526e7b">

---

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH @petermetz

**Comment by krisstern** [comment]
Hi, I would like to work on this issue.

**Comment by petermetz** [comment]
> Hi, I would like to work on this issue.

@krisstern Of course! Thank you in advance for your contributions!
We have a daily pair programming on discord at 10 AM Pacific Time on most weekdays so feel free to drop in there as well if you have any questions.

**Comment by krisstern** [comment]
Thanks @petermetz! Sure, I will drop in to the daily pair programming on Discord in case I have any questions.
