### ISSUE TITLE
fix(test-verifier-client): ssl verification bypass

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2764]
## Description
Static source code assessment has picked up a potential vulnerability regarding ssl verification bypass. The possible fix can include an argument passed, which enables/disables it based on prod/test environments.

## The report from which the above information was summarised
Risk Rating: Medium
Category: Security Misconfiguration

### Description
The application utilizes HTTPS but is explicitly configured to disable verification of certificate authenticity. If the certificate signer is not verified all the way up to a trusted certificate authority, it is possible to issue a bogus certificate, and have it be accepted by the application. Since the application does not enforce the signing certificate is already configured in the system's trusted root certificate store, it is possible to simply use a self-signed certificate, with any user- or server-name, and the application will trust it.

### Impact
If the SSL/TLS library is configured to disable verification of the certificate's properties, such as trust chain, hostname, expiry and more - it is possible to cause the application to utilize an unvalidated certificate. This may allow an attacker to intercept the client requests, provide their own forged server certificate, and perform an active Man-in-the-Middle attacks - even over HTTPS. Thus an attacker would have complete access to the content of requests and responses, reading any secret information and tampering any sensitive data, including user credentials.

### Remediation Recommendation
• Properly implement all checks necessary to ensure the identity of entities involved in encrypted communications.
• Properly configure all parameters of HTTPS.
• Never disable certificate verification.
• Explicitly enforce verification, setting "rejectUnauthorized" to True.

### Affected files (path - line number)

packages/cactus-test-verifier-client/src/main/typescript/verifier-with-go-eth-stress-check.ts - 149

## Snapshot of the sourcecode at the time of scan

<img width="672" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/428214d6-5ee1-4d72-bcf5-529aaa3de9ed">
---

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH @petermetz

**Comment by outSH** [comment]
@jagpreetsinghsasan This script is meant to be run against development instance of a connector, setting up PKI just to run it would be combersome. I'm not sure how to solve it otherwise since the warning states that verification should be enforced at all times (so we shouldn't "trick" it with reading config from envvar or config).

**Comment by petermetz** [comment]
@outSH No worries, I'll close it as wont fix then (I asked Jagpreet to open these issues based on the report we've got back internally)
