### ISSUE TITLE
fix(weaver): usage of weak PRNG 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2765]
## Description
Static source code assessment has picked up a potential vulnerability regarding use of weak pseudo RNG. Use of secure pseudo random number generators rather than using basic random methods can fix the above vulnerability

## The report from which the above information was summarized
Risk Rating: Low
Category: Security Misconfiguration

### Description
The application uses a weak method of generating pseudo-random values, such that other numbers could be determined from a relatively small sample size. Since the pseudo-random number generator used is designed for statistically uniform distribution of values, it is approximately deterministic. Thus, after collecting a few generated values, it would be possible for an attacker to calculate past or future values. These values are then used as parameters in a cryptographic function. If an attacker were to obtain the original value from the weak PRNG, they may be able to predict or crack values produced by the cryptographic function.

### Impact
Depending on what this random value is used for, an attacker with knowledge of the PRNG used would be able to predict the next values generated, or previously generated values, based on sources often used to derive certain randomness; however, while they may seem random, large statistical samples would demonstrate that they are insufficiently random, producing a much smaller space of possible "random" values than a truly random sample would. In the context of cryptography, this could enable an attacker to derive or guess the value, and thus crack the cryptographic mechanism or its outputs.

### Remediation Recommendation
• Always use a cryptographically secure pseudo-random number generator, instead of basic random methods, particularly when dealing with a security context such as cryptographic functions
• Use the cryptorandom generator that is built-in to your language or platform, and ensure it is securely seeded. Do not seed the generator with a weak, non-random seed. (In most cases, the default is securely random). 
• Ensure you use a long enough random value, thus making brute-force attacks unfeasible.

### Affected files (path - line number)

weaver/core/network/fabric-interop-cc/contracts/interop/certificate_utils.go - 304
weaver/sdks/corda/src/main/kotlin/org/hyperledger/cacti/weaver/sdk/corda/HashFunctions.kt - 46
weaver/sdks/fabric/interoperation-node-sdk/src/eciesCrypto.js - 177

## Snapshot of the sourcecode at the time of scan

<img width="610" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/a7cfee3a-39c2-46d2-9732-9548991d575c">
<img width="620" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/4e721822-9bd2-4fa0-a6f4-9e350f9262d1">
<img width="558" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/3a5e2ace-21c7-4745-baf3-04f2ea30c7d1">

---

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH @petermetz

**Comment by VRamakrishna** [comment]
The PR used for the fix had an error as indicated in the comments starting from https://github.com/hyperledger/cacti/pull/2907#issuecomment-1855746888. Reopening this issue to create another PR for a more complete fix.
