### ISSUE TITLE
fix(test-tooling): use of hardcoded password

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2766]
## Description
Static source code assessment has picked up a potential vulnerability regarding use of hardcoded password.

## The report from which the above information was summarized
Risk Rating: Low
Category: Sensitive data exposure

### Description
The application codebase has string literal passwords embedded in the source code. This hardcoded value is used either to compare to user-provided credentials, or to authenticate downstream to a remote system (such as a database or a remote web service).  

### Impact
Hardcoded passwords expose the application to password leakage. If an attacker gains access to the source code, she will be able to steal the embedded passwords, and use them to impersonate a valid user. This could include impersonating end users to the application, or impersonating the application to a remote system, such as a database or a remote web service. Once the attacker succeeds in impersonating the user or application, she will have full access to the system, and be able to do anything the impersonated identity could do.

### Remediation Recommendation
Do not hardcode any secret data in source code, especially not passwords. In particular, user passwords should be stored in a database or directory service, and protected with a strong password hash (e.g. bcrypt, scrypt, PBKDF2, or Argon2). Do not compare user passwords with a hardcoded value. 
System passwords should be stored in a configuration file or the database, and protected with strong encryption (e.g. AES-256). Encryption keys should be securely managed, and not hardcoded.

### Affected files (path - line number)

packages/cactus-test-tooling/src/main/typescript/openethereum/openethereum-test-ledger.ts - 236

## Snapshot of the sourcecode at the time of scan

<img width="546" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/49d4f3a7-a0c6-4e47-bdba-5e194d6db9cb">
---

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH @petermetz

**Comment by ShatilKhan** [comment]
Hi @jagpreetsinghsasan 
Please assign me this issue

**Comment by petermetz** [comment]
@ShatilKhan All yours!

**Comment by ashnashahgrover** [comment]
Can you assign me this issue.
