### ISSUE TITLE
fix(weaver): improper exception handling

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2767]
## Description
Static source code assessment has picked up a potential vulnerability regarding improper exception handling. The possible remediation for the same is to have it enclosed within a try catch block and handle the exceptions accordingly.

## The report from which the above information was summarized
Risk Rating: Low
Category: Security Misconfiguration

### Description
The application performs some operation, such as database or file access, that could throw an exception. Since the application is not designed to properly handle the exception, the application could crash.

### Impact
An attacker could maliciously cause an exception that could crash the application, potentially resulting in a denial of service (DoS) or unexpected behavior under certain erroneous conditions. Exceptions may also occur without any malicious intervention, resulting in general instability.

### Remediation Recommendation
Any method that could cause an exception should be wrapped in a try-catch block that:
• Explicitly handles expected exceptions.
• Includes a default solution to explicitly handle unexpected exceptions.

### Affected files (path - line number)

weaver/sdks/corda/src/main/kotlin/org/hyperledger/cacti/weaver/sdk/corda/CredentialsExtractor.java - 294,295

## Snapshot of the sourcecode at the time of scan

<img width="605" alt="image" src="https://github.com/hyperledger/cacti/assets/56861721/e35e510c-a8a5-46b8-a30f-d4c1c59e177b">
---

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH @petermetz

**Comment by Yogesh01000100** [comment]
Hey @jagpreetsinghsasan  In the exception block, should we primarily focus on logging the exception for debugging, or are there specific actions that need to be taken when an exception occurs?

**Comment by petermetz** [comment]
@Yogesh01000100 I would focus on logging+re-throw. 
1. E.g., if something goes here wrong, I'd say it's best to crash
2. But crash with information about what was being done so that it will be easier for people looking at the crash logs afterwards to figure out how to fix it.

**Comment by Yogesh01000100** [comment]
May I be assigned this issue? now that I have a better understanding of the task

**Comment by petermetz** [comment]
@Yogesh01000100 All yours!
