### ISSUE TITLE
feat(satp-hermes): refactor package

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cacti#2809]
Update the naming ODAP to SATP to reflect the evolution of the protocol. 

**Describe the solution you'd like**
Rename ODAP-HERMES to SATP-Hermes (core, examples).

@petermetz please assign it to me. @AndreAugusto11 and I are managing these tasks.

**Comment by AndreAugusto11** [comment]
@RafaelAPB When addressing this issue, a good addition to the REAMDE is mentioning the current version of the SATP draft being used

**Comment by petermetz** [comment]
@RafaelAPB @AndreAugusto11 Assigned it, thank you for the contributions in advance!

**Comment by RafaelAPB** [comment]
@AndreAugusto11 yes, we can refer to the current editor's copy: https://github.com/ietf-satp/draft-ietf-satp-core
