### ISSUE TITLE
docs(examples/cbdc): remove chaincode's dependency on IDs passed by the frontend

### ISSUE THREAD

**Issue by AndreAugusto11** [hyperledger/cacti#2816]
**Is your feature request related to a problem? Please describe.**
Following [this](https://github.com/hyperledger/cacti/commit/43980b0cb9e2f19ea550a3a1941b6b7099ef8a1c#commitcomment-130288189) commit comment.

Currently, the Fabric identities of the users making requests to the CBDC chaincode, provide their identities in plain text. Even though this is an example, we should improve its security.

Additionally, if there is a change in the Fabric SDK, these hardcoded values need to be changed accordingly, originating problems just like the one solved by #2802.

**Describe the solution you'd like**
The chaincode should perform identity checks based on the caller's context and not on arguments.

@petermetz can assign this to me pls

Thanks @RafaelAPB

**Comment by petermetz** [comment]
@AndreAugusto11 Done, thank you!

**Comment by AndreAugusto11** [comment]
Closed by #2912
