### ISSUE TITLE
docs(examples/cbdc): migrate frontend implementation from JS to TS

### ISSUE THREAD

**Issue by AndreAugusto11** [hyperledger/cacti#2817]
**Is your feature request related to a problem? Please describe.**
The frontend is written in JavaScript instead of Typescript. To be consistent with the rest of the codebase and the monorepo, the code should be migrated to Typescript.

@petermetz can assign this to me pls

**Comment by petermetz** [comment]
@AndreAugusto11 Done, thank you!
