### ISSUE TITLE
feat(cactus-example-tcs-huawei): use openapi ethereum connector

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#2820]
**Is your feature request related to a problem? Please describe.**
We are phasing out legacy `cactus-plugin-ledger-connector-go-ethereum-socketio` which is used by `cactus-example-tcs-huawei` sample app. This old connector must be replaced with new, openapi based one - `cactus-plugin-ledger-connector-ethereum`.

**Describe the solution you'd like**
Refactor sample app to use `cactus-plugin-ledger-connector-ethereum` (similar work to this PR - https://github.com/hyperledger/cacti/pull/2735).

@123wyl123 please investigate and let me know if you can do it :)

**Comment by outSH** [comment]
@123wyl123 any updates regarding updating of tcs sample app?

**Comment by 123wyl123** [comment]
@outSH  Sorry for  replying to your message now.
I will revise the implementation of that part and submit it as soon as possible

**Comment by outSH** [comment]
@123wyl123 I'm happy to hear that! If you encounter any trouble please reach out to me :) 

Another thing which would be nice to do before our V2 release is to upgrade [cactus-plugin-ledger-connector-tcs-huawei-socketio](https://github.com/hyperledger/cacti/tree/main/packages/cactus-plugin-ledger-connector-tcs-huawei-socketio) you've contributed to openapi-based connector. Example of simple openapi connector to get the idea is here - https://github.com/hyperledger/cacti/pull/2962

Please let me know if you can do that as well

**Comment by petermetz** [comment]
@123wyl123 Plus one to what @outSH said above! I'm happy to help as well!

**Comment by outSH** [comment]
@123wyl123 Hello, do you have any questions or problems regarding this? Please note that I've also opened a separate issue for open-api migration that I've mentioned in a previous comment (which is also important since it blocks removal of socketio-server) - https://github.com/hyperledger/cacti/issues/3076

**Comment by petermetz** [comment]
Closing this for now because we've phased out the components in question.
