### ISSUE TITLE
feat(satp-hermes): implement BUNGEE

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cacti#2826]
Implement BUNGEE blockchain views for SATP. BUNGEE paper: https://www.techrxiv.org/articles/preprint/Is_My_Perspective_Better_Than_Yours_Blockchain_Interoperability_with_Views/20025857

@petermetz please assign me this issue

**Comment by petermetz** [comment]
@RafaelAPB Done, thank you! :-)

**Comment by AndreAugusto11** [comment]
@petermetz can you give us a hand here pls?

Within my fork, there's a branch named `bungee-refactor`, with a commit from each of us (@RafaelAPB and myself). We added a new plugin there called `cactus-plugin-bungee`. However, upon executing `yarn run configure`, we encounter several dependency conflicts (that seem unrelated).

I am attaching a log file. If it helps I can create a draft PR to see the differences between this branch and the main one.

[broken-build.log](https://github.com/hyperledger/cacti/files/13660599/broken-build.log)

**Comment by eduv09** [comment]
Please add me as an assignee

**Comment by petermetz** [comment]
@AndreAugusto11 Sorry I'm very late to responding to this. I'm checking it now.

**Comment by AndreAugusto11** [comment]
Hey @petermetz no worries! TBH I don't remember what was the problem, but I'm pretty sure we managed to solve it!

**Comment by petermetz** [comment]
@AndreAugusto11 OK, that's good to know, thank you! :-)

**Comment by RafaelAPB** [comment]
This is actually done!
