### ISSUE TITLE
Corda Validators are not found in  examples/cartrade

### ISSUE THREAD

**Issue by sillysachin** [hyperledger/cacti#285]
In the premise section Launch two Validators (For ethereum and fabric) is documented.

Is there a separate branch for corda example with fabric. Is this pending work?

**Comment by petermetz** [comment]
cc: @takeutak @sfuji822

**Comment by outSH** [comment]
cartrade was removed, remaining discounted-asset-trade supports fabric, ethereum and indy ledgers only
