### ISSUE TITLE
Getting 'ipfs-http-client' error while starting cbdc app

### ISSUE THREAD

**Issue by Anusha-Padmanabhan** [hyperledger/cacti#2852]
**Describe the bug**

While starting cbdc app using command `npm run start:example-cbdc-bridging-app`
Getting the following error
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/ubuntu/cactus/cacti/extensions/cactus-plugin-object-store-ipfs/node_modules/ipfs-http-client/package.json
<img width="509" alt="cbdc_error" src="https://github.com/hyperledger/cacti/assets/119853495/7234c0c7-f44c-4541-91dc-67f5f7d69a6f">

I am unable to test the issue - https://github.com/hyperledger/cacti/issues/2739

Related issues :
https://github.com/hyperledger/cacti/issues/2759
https://github.com/hyperledger/cacti/issues/2739

**To Reproduce**

Start the app using command  `npm run start:example-cbdc-bridging-app`

**Expected behavior**

Application should start without any errors

**Screenshots**

**Cloud provider or hardware configuration:**
Are you running the software on a dev machine or somewhere in the cloud?

**Operating system name, version, build:**

Use this command: `printf "$(uname -srm)\n$(cat /etc/os-release)\n"`

For example

```sh
$ printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Linux 4.15.0-70-generic x86_64
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

Either a semantic version of the release you are using such as `1.0.0` or a git
commit hash if you are directly working with code from the git repository.

**Hyperledger Cactus Plugins/Connectors Used**

 - Which DLT connectors are you using (Fabric, Quorum, Corda, Besu, etc.)

**Additional context**

**Comment by outSH** [comment]
Thanks for the report! This issue is currently being fixed as part of https://github.com/hyperledger/cacti/issues/2807
