### ISSUE TITLE
docs(examples/cbdc): fix mismatch of fabric identities

### ISSUE THREAD

**Issue by ak1334** [hyperledger/cacti#2914]
**Describe the bug**

While setting up the ""cactus-example-cbdc-bridging", getting the error while performing the Escrow or Transfer functionality of the CBDC tokens.

**To Reproduce**

Clone cacti main branch with commit(e171d15) and try to run the CBDC bridging example and perform mint or transfer CBDC.

**Expected behaviour**

Minted CBDC should get transferred to the respective accounts after clicking on the transfer  button as well as the escrow functionality should behave as expected to perform the bridge out functionality.

**Logs/Stack traces**

Error Details  :  Unable to run transaction: No valid responses from any peers. Errors:  peer=peer0.org1.example.com, status=500, message=client account x509::/OU=org1/OU=client/OU=department1/CN=userB::/C=US/ST=North Carolina/L=Durham/O=org1.example.com/CN=ca.org1.example.com has no balance .     

**Screenshots**
![transfer-error](https://github.com/hyperledger/cacti/assets/7413389/a9e696a7-2256-4a27-bc5a-503e3fcac826)

**Operating system name, version, build:**
Linux 5.15.0-88-generic x86_64
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

Main branch commit : e171d15

**Hyperledger Cactus Plugins/Connectors Used**

 - Hyperledger BESU and FABRIC Connectors are used.  

**Additional context**
@AndreAugusto11

**Comment by AndreAugusto11** [comment]
Thank you @ak1334

**Comment by petermetz** [comment]
@ak1334 I just merged the PR to fix this, you can re-test on the main branch and see if it works!

**Comment by ak1334** [comment]
@petermetz , Thanks for the updating, I will check.
