### ISSUE TITLE
Supply-chain-app - Build failed

### ISSUE THREAD

**Issue by ak1334** [hyperledger/cacti#2945]
**Describe the bug**
Supply chain app is not starting and failing during the build process.

**To Reproduce**
Clone the latest cacti repo. commit ([66f65a8]
Run below command s:
> npm run enable-corepack
> npm run configure
> yarn start:example-supply-chain

After the final command, it gives the build error

**Expected behavior**
Supply chain app should start and load the front-end in the browser

**Logs/Stack traces**
Getting below errors : 

lerna-lite ERR! yarn run build:dev:frontend exited 1 in '@hyperledger/cactus-example-supply-chain-frontend'
lerna-lite ERR! yarn run build:dev:frontend stderr:

../../packages/cactus-api-client/dist/cactus-api-client.web.umd.js - Warning: Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://cactus-api-client/cactus-common/index.ts' URL is not supported

../../packages/cactus-api-client/dist/cactus-api-client.web.umd.js - Warning: Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://cactus-api-client/cactus-common/key-encoder.ts' URL is not supported

../../packages/cactus-api-client/dist/cactus-api-client.web.umd.js - Warning: Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://cactus-api-client/cactus-common/webpack/after-startup' URL is not supported

**Screenshots**

**Operating system name, version, build:**
Linux 5.15.0-88-generic x86_64
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**
https://github.com/hyperledger/cacti/commit/66f65a80e60c1c8142bdc9108c5bf6bca9069876

**Hyperledger Cactus Plugins/Connectors Used**

 -  DLT connectors used : Fabric, Quorum, Besu for supply-chain-app

**Additional context**
@petermetz 
@VRamakrishna

**Comment by petermetz** [comment]
@ak1334 Sorry, there is an on-going bug-fix [1] for the supply chain example right now.
With that said, it doesn't look the like errors you are showing on the screenshots are the real errors. Could you please save the full log output to a text file and attach that? With that I could at least confirm if you are having the same issue as #2721 or a different one.

[1] https://github.com/hyperledger/cacti/issues/2721

**Comment by ak1334** [comment]
Hi @petermetz , sharing the complete error-log file as requested.
[error-log.txt](https://github.com/hyperledger/cacti/files/13643842/error-log.txt)

**Comment by ak1334** [comment]
As i have cloned the latest repo., now getting below error, Im not getting the above mentioned error anymore : 

error : Unknown Syntax Error: Unsupported option name ("--no-lockfile")
![error_logs](https://github.com/hyperledger/cacti/assets/7413389/d2a181bd-0490-406a-8004-dfa9f46901c4)

**Comment by petermetz** [comment]
@ak1334 Progress update: I'm in the process of migrating the supply chain app's fabric contract onto Fabric 2.5.x (current LTS) which should implicitly take care of the problems experienced in this issue as well! I'll keep this issue posted, please bear with me!

**Comment by petermetz** [comment]
@ak1334 Sorry for the slow response! The supply chain example should be working now!
