### ISSUE TITLE
feat(openapi): java clients for packages affected by openapi bug

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#2970]
### Description
As a developer, I want to generate the java clients for the following packages (dividing them into 2 parts, grouped on the error currently pesistent as of 5th January 2024)

Part A
`cactus-core-api`

Part B
`cactus-plugin-htlc-eth-besu`
`cactus-plugin-htlc-eth-besu-erc20`
`connector-besu`
`connector-ethereum`
`connector-quorum`
`connector-xdai`

Part C
`connector-iroha`
`connector-iroha2`

For more reference, please refer to the comments, starting from: https://github.com/hyperledger/cacti/issues/393#issuecomment-1874926861

### Acceptance Criteria
1. The java client generation should happen and should be a part of the workflow present here `.github/workflows/ghpkg-all-java-api-clients-publish.yaml`

**Comment by krisstern** [comment]
Hi, I would like to work on this issue

**Comment by petermetz** [comment]
@krisstern Hmm. I'm not sure if this one is still available. I see that it hasn't been assigned to anyone but at the same time I remember seeing pull requests on this topic so I'll have to ask @jagpreetsinghsasan to confirm if he is working on it or not just to  be sure. Jagpreet could you let us know if this is really available?

**Comment by jagpreetsinghsasan** [comment]
@petermetz its available `if` we are to generate the java code using `-g java` argument. Can answer this question once the ongoing conversation here gets resolved: https://github.com/hyperledger/cacti/pull/2973#issuecomment-2042130024

**Comment by petermetz** [comment]
> @petermetz its available `if` we are to generate the java code using `-g java` argument. Can answer this question once the ongoing conversation here gets resolved: [#2973 (comment)](https://github.com/hyperledger/cacti/pull/2973#issuecomment-2042130024)

Yeah, it's my fault, sorry about the misunderstanding @jagpreetsinghsasan and @krisstern .
Basically what I meant by "java clients" is JVM in general (e.g. Kotlin in our case)

**Comment by jagpreetsinghsasan** [comment]
Based on the conversations I had with @petermetz around this on my previous PR, I will create new issues to address the same.
Because when I created this task, the intention was to generate the jars using Java codegen specifically (which is very buggy at the moment). But now with the clarification. I will create another issue listing all the plugins which needs the jars (can be generated by either kotlin/java, whatever codegen works).
@krisstern I will tag you in the comment section of that task.

**Comment by krisstern** [comment]
@jagpreetsinghsasan That would be great! I would appreciate it
