### ISSUE TITLE
docs(examples): upgrade to Angular v17.x.x project-wide

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#3063]
### Description

The documentation should be up to date so that we don't get caught off-guard with dependencies in the form of people having used the examples as their templates for Cacti based projects (which happens a lot)

https://github.com/angular/angular/releases/tag/17.3.0-rc.0

### Acceptance Criteria
1. The supply chain app build is passing and has been upgraded to the latest Angular version.
2. If need be Ionic dependencies were upgraded as well.
3. All the above but also applied to the carbon accounting example (which is as of yet incomplete)
4. Overall the diff for the pull requests is the absolute minimum size it has to be, e.g. nothing else is included in it just the upgrade and any code changes that were necessary due to the upgrade.

**Comment by aldousalvarez** [comment]
Hello @jagpreetsinghsasan I would like to work on this one. Thank you
