### ISSUE TITLE
test(connector-polkadot): fix broken tests (all) due to ESM imports

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#3077]
### Description

I remember running the tests of the polkadot PR at some point and them passing, but now they appear as if they were always broken /facepalm.

Logs: 
[2024-02-27T21-38-00-cacti-polkadot-connector-test-failures.log](https://github.com/hyperledger/cacti/files/14561235/2024-02-27T21-38-00-cacti-polkadot-connector-test-failures.log)

@AnmolBansalDEV Do you remember when the tests broke and what change triggered it?

### Acceptance Criteria
1. Tests are passing

**Comment by outSH** [comment]
@petermetz I think when you add new tests to CI they do not run in that particular PR (i.e. CI file is taken from main, not the branch that is being merged), and this suite has been failing from the beginning.

**Comment by petermetz** [comment]
> @petermetz I think when you add new tests to CI they do not run in that particular PR (i.e. CI file is taken from main, not the branch that is being merged), and this suite has been failing from the beginning.

@outSH Damn. Sorry I missed that and thank you for noticing this hole in our review process.
