### ISSUE TITLE
Consortium-level privacy

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cacti#3109]
Provide the option for gateways to assign privacy levels on view generation and processing, within the context of SATP.

Requirements:
1. Define processes for consortium members to agree on privacy properties for view creation, processing, merging, and transfer.
1. Negotiation phase at consortium creation to define desirable privacy properties
2. Extend Consortium schema to have (an optional) BUNGEE privacy config (e.g., which processing algorithm, how to merge views, refer to the paper): packages/cactus-core-api/src/main/json/openapi.json and packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts)
3. Pass those arguments from the Cacti node to the SATP instance. Pass such options from the SATP instance to the BUNGEE instance.
4. Update Prometheus metrics to track privacy properties chosen

**Comment by eduv09** [comment]
@RafaelAPB please assign me this one

**Comment by RafaelAPB** [comment]
replaced by #3122
