### ISSUE TITLE
feat(cactus-example-tcs-huawei): remove deprecated sample app

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#3157]
**Is your feature request related to a problem? Please describe.**
`cactus-example-tcs-huawei` is using `cactus-plugin-ledger-connector-go-ethereum-socketio` and `cactus-plugin-ledger-connector-tcs-huawei-socketio`, both of them will be removed soon as well. Ths sample app can't exist without them.

**See #3155 for more details on motivation and future of this package!**

#### Deprecation and package removal is not final
If there's a need to bring some of these packages back, or if the package gets refactored so that it matches
the state of other cacti packages, then the package can be restored. Removed packages can still be accessed by checking-out the state of this repo before the removal (I'll add appropriate commits next to the removed plugins on the list as the PR get merged).

**Comment by petermetz** [comment]
@outSH Thank you! I posted some additional details on the pull request itself just to make sure everyone is in the know about the details of our decision here and that the removal is just temporary.
