### ISSUE TITLE
feat(cactus-plugin-ledger-connector-iroha): remove deprecated iroha connector

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#3159]
**Is your feature request related to a problem? Please describe.**
Iroha connector is broken for some time and it's SDK does't seem to be actively supported anymore (in regards of bug or security fixes).

**Describe the solution you'd like**
We should remove this package

Part of: https://github.com/hyperledger/cacti/issues/3155

**Comment by petermetz** [comment]
Agreed!
