### ISSUE TITLE
Unable to run fabric weaver driver 

### ISSUE THREAD

**Issue by thobbyAk** [hyperledger/cacti#3213]
<img width="1391" alt="Screenshot 2024-04-17 at 17 38 06" src="https://github.com/hyperledger/cacti/assets/71441407/6e5c8b79-2bf2-4281-ab65-1a46818c1c42">

## Describe the bug

I am trying to run fabric driver . after configuring my .env file , i try to build the fabric driver locally and i get the above error 

**To Reproduce**
- Navigate to weaver/core/drivers/fabric-driver module and run `make build-local `
make sure to have all the necessary dependencies installed.

**Expected behavior**

- Build should be successful

**Logs/Stack traces**

- Can maintainers help identify root causes and profer solution

**Screenshots**
<img width="1391" alt="Screenshot 2024-04-17 at 17 38 06" src="https://github.com/hyperledger/cacti/assets/71441407/6e5c8b79-2bf2-4281-ab65-1a46818c1c42">

**Cloud provider or hardware configuration:**
- Hetzner Cloud 

**Operating system name, version, build:**
- Ubuntu 22.044 Lts
-npm version 8.5.1

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**
Latest

**Hyperledger Cactus Plugins/Connectors Used**

 -Fabric

**Additional context**

- Trying to run the relay and driver components for interop

**Comment by outSH** [comment]
Hello, try building weaver using out script that makes sure to cleanup any remaining artifacts from previous build, let me know if there are any errors: `bash tools/weaver-build-local.sh`

@VRamakrishna @sandeepnRES any other suggestions?

**Comment by thobbyAk** [comment]
> Hello, try building weaver using out script that makes sure to cleanup any remaining artifacts from previous build, let me know if there are any errors: `bash tools/weaver-build-local.sh`
> 
> @VRamakrishna @sandeepnRES any other suggestions?
I get this error saying " protoc-gen-go: command not found "
<img width="955" alt="Screenshot 2024-04-19 at 09 55 32" src="https://github.com/hyperledger/cacti/assets/71441407/f3e53198-3a98-4d8b-bbf9-66dd676f0ec8">
