### ISSUE TITLE
feat(connector-stellar): Connector and Validator

### ISSUE THREAD

**Issue by fazzatti** [hyperledger/cacti#3238]
**Is your feature request related to a problem? Please describe.**
One should be able to connect and interact with the Stellar network through both their Classic(native operations) and Soroban(Smart contracts platform) to build interoperable use cases with other networks.

**Describe the solution you'd like**
The connector should:
- Implemented active behavior through Stellar Classic to
  - Create and submit transactions
  - Support native transaction operations
- Implement active behavior through Stellar Soroban to
  - Deploy, manage, and invoke smart contracts
  - Create, simulate, and submit smart contract transactions
- Leverage stellar-related best practices

**Additional context**
I'm starting this initiative to integrate the Stellar network into Hyperledger cacti on behalf of [Cheesecake Labs](https://cheesecakelabs.com/). We aim at having a connector plugin able to handle interoperability with the Stellar network and leverage different use cases that can benefit from both the Classic and Soroban types of transactions supported by Stellar.

**Comment by fazzatti** [comment]
Another issue has just been opened to cover the first step as creating the Stellar Test Ledger here: https://github.com/hyperledger/cacti/issues/3239

**Comment by fazzatti** [comment]
Created this branch to follow with progress specific to the connector here https://github.com/fazzatti/cacti/tree/plugin-stellar-connector

Currently, it is possible to run tests to fully deploy a contract with:

```bash
yarn jest packages/cacti-plugin-ledger-connector-stellar/src/test/typescript/integration/plugin-ledger-connector-stellar/deploy-contract/
```

There are a few workarounds in there which I'll fix next as they require some small tweaks to https://github.com/CheesecakeLabs/stellar-plus as well.

**Comment by RafaelAPB** [comment]
Happy to help reviewing the PR when you have a first draft! Thanks for your contribution

**Comment by petermetz** [comment]
@fazzatti Thank you for the contributions in advance! Looking forward to this making it to `main` :-)
