### ISSUE TITLE
test(stellar-test-ledger): Stellar Test Ledger

### ISSUE THREAD

**Issue by fazzatti** [hyperledger/cacti#3239]
**Is your feature request related to a problem? Please describe.**
Implement a Test Ledger able to pull up a docker image with a stellar network core, validators, and necessary services(Horizon API, Soroban RPC, and Friendbot) to run Stellar-related Cacti tests against.

**Describe the solution you'd like**
The Stellar Test Ledger should:
- Start, stop, and destroy a docker container with the test ledger.
- Contains all the necessary services to execute complete use cases in Stellar.
  - Horizon API server for interacting with the Stellar network.
  - Soroban RPC for interacting with smart contracts.
  - Friendbot for starting and funding accounts in a test environment.
- Ensure all services are available before allowing the tests to be executed.
- Allow for an ephemeral pristine local ledger to be started with no history.

**Additional context**
This is the first step of the initiative mention in the issue https://github.com/hyperledger/cacti/issues/3238 .

**Comment by RafaelAPB** [comment]
Happy to help reviewing the PR when you have a first draft! Thanks for your contribution
