### ISSUE TITLE
Enable OpenSSF Scorecard to periodically track the project's health

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger/cacti#3268]
**Is your feature request related to a problem? Please describe.**
Track OpenSSF health criteria as agreed on in the Hyperledger TOC meeting on May 16, 2024. (See charts presented in the call at https://docs.google.com/presentation/d/18zO30diSW1jUfQwoglWza0Lx2_Q8vwuE__q-JdoC3ho/edit#slide=id.g2dd524f49cb_0_0)

**Describe the solution you'd like**
Open a GitHub action similar to what's already been deployed for Hyperledger Fabric: https://github.com/hyperledger/fabric/blob/main/.github/workflows/scorecard.yml.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ashnashahgrover** [comment]
Please assign me this issue.

**Comment by jagpreetsinghsasan** [comment]
Completed via PR: https://github.com/hyperledger/cacti/pull/3302
