### ISSUE TITLE
Privacy leakage in asset_transfer.go

### ISSUE THREAD

**Issue by pdchecker** [hyperledger/cacti#3273]
**Describe the bug**
Privacy leakage in packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/asset-transfer-private-data/chaincode-go/chaincode/asset_transfer.go. The functions that query private data should be read-only.

**To Reproduce**
1. Deploy asset_transfer.go, along with the PDC definition.
2. Invoke the AgreeToTransfer function to write the private data P to the PDC.
3. Fetch the block and find corresponding transaction.
4. The private data P can be found in "payload" field

**Expected behavior**
The private data will be included in the transaction and all peers can access.

**Screenshots**
The private data is recorded in base64.
![image](https://github.com/hyperledger/cacti/assets/169994828/d07c02ae-dafb-4aac-9b24-423744b6bec3)

**Operating system name, version, build:**
OS: Ubuntu 22.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**
Hyperledger Fabric2.4.7

**Additional context**
Leakage occurs in line 102, 214, 290, 309, 317, 446, 460, 529

**Comment by petermetz** [comment]
@pdchecker That one is just a test fixture, not used in production. Thank you for the report!
