### ISSUE TITLE
feat(connector-daml): aio image 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#3284]
### Description
As a developer, I want to create an all in one image dockerized ledger for DAML platform, so that we can use that aio in our DAML connector via test tooling class

Reference: https://docs.daml.com/getting-started/index.html#

### Acceptance Criteria
1. `daml-all-in-one` available under `tools/docker` folder
2. The dockerized container should have the appropriate healthchecks
3. The ledger should be accesible from outside the container via the client libraries/rpc (whatever is applicable)
4. Readme within the aio folder mentioning how to build & run a daml ledger docker image

**Comment by raynatopedrajeta** [comment]
Hello @jagpreetsinghsasan  and @petermetz ,

Please assign this ticket to me since I already started the RnD on this item.

Thanks!

Ren
