### ISSUE TITLE
Running cactus-example-discounted-asset-trade is causing errors

### ISSUE THREAD

**Issue by rajat-dlt** [hyperledger/cacti#3335]
**Describe the bug**

I plan to develop a bridge using Hyperledger Cactus between Ethereum and Hyperledger Fabric. While reviewing the examples, I found the cactus-example-discounted-asset-trade example, which seems like a great starting point.

There are two issues:
1. The script-start-ledgers.sh script doesn't work because the application uses V2_5, while the peer/orderer images use 2.4. I resolved this by updating the versions as follows, these version were obtained from the bashing inside the docker image:
    ```
    export CACTUS_FABRIC_ALL_IN_ONE_VERSION="2.5.6"
    export CACTUS_FABRIC_ALL_IN_ONE_NODEENV_VERSION="2.5.4"
    ```
1. The yarn setup-credentials command still fails with the error described below.

**To Reproduce**

1. Cleaned up everything by running `sudo ./script-cleanup.sh` and `./script-cleanup.sh` in `cactus-example-discounted-asset-trade`.
1. Made the following changes in `script-start-ledgers`:
    ```
    export CACTUS_FABRIC_ALL_IN_ONE_VERSION="2.5.6"
    export CACTUS_FABRIC_ALL_IN_ONE_NODEENV_VERSION="2.5.4"
    ```
1. Ran the ledger using the following script: `./script-start-ledgers.sh &> out.txt`
1. Following the commands mentioned in README ran the following command, in a separate shell
   ```
   cd ./examples/cactus-example-discounted-asset-trade-client
   LOG_LEVEL=debug yarn setup-credentials &> out.txt
   popd
   ```

**Expected behavior**

The commands should run and all the credentials should be generated. 

**Logs/Stack traces**

Log for the command, `./script-start-ledgers.sh`: https://hastebin.skyra.pw/foqotikeju.shell
Log for the command, `yarn setup-credentials`:  https://hastebin.skyra.pw/upanuvagej.swift
Logs of `asset_trade_indy_all_in_one` container:  https://hastebin.skyra.pw/rivevayora.pgsql
**Screenshots**

Added comprehensive logs along with this. 

**Cloud provider or hardware configuration:**
Running this on a dev machine.

**Operating system name, version, build:**

Darwin 22.6.0 x86_64
node v20.11.1 (npm v10.2.4)

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):
fa6cb101e

**Hyperledger Cactus Plugins/Connectors Used**

 - Nothing apart from the ones used in the example.

**Additional context**

Once the problem occurs, the following error is observed on subsequent attempts: https://hastebin.skyra.pw/uporepidar.swift.

It seems like the error is in:
```
  await agent.dids.import({
    did,
  });
```
but I haven't been able to pinpoint exactly what's missing.

**Comment by petermetz** [comment]
cc:  @izuru0 @outSH @takeutak

**Comment by rajat-dlt** [comment]
I continued working on this issue and tried resolving it by updating the following code in the agent-setup.ts file:
```
- await agent.dids.import({
+ await agent.dids.create({
```

This allowed the process to proceed a bit further, but it is still not fully resolved. Here are the logs after the update: [Logs](https://hastebin.skyra.pw/davajisoli.swift).

Could you please help me resolve this?

**Comment by rajat-dlt** [comment]
The example seems to be working fine on linux environment, after merging the PRS. 
We can close this now.

**Comment by petermetz** [comment]
@rajat-dlt Nice, thank you very much for confirming and sorry for the slow responses!
