### ISSUE TITLE
feat(daml): test tooling class

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cacti#3435]
## Description
As a developer, I want to create a test tooling class for the daml AIO. This class will enable us to use the AIO programmatically once we create the connector class.

## References
[Test tooling class for besu](https://github.com/hyperledger/cacti/blob/main/packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts)
[Sample test case utlizing this test tooling class](https://github.com/hyperledger/cacti/blob/main/packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/v21-besu-get-transaction.test.ts)

## Acceptance Criteria
1. Daml test tooling class to be created
2. A test case utilizing the same to showcase AIO use (this shouldn't be a part of PR, but should be showed prior PR creation)

**Comment by raynatopedrajeta** [comment]
Hello Team,
Please assign this item to me.

Cheers!

Rayn
