### ISSUE TITLE
[design] obtain input from ledgers maintainers regarding Cactus v0.3.0

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#369]
### Description

At one of our bi-weekly calls it came up as a suggestion (thank you @brianbehlendorf) that we should solicit feedback from maintainers of ledgers we aim to support rather earlier than later to lower the cost of design decisions that may turn out to be sub-optimal in the future. 
More specifically: we don't want to start soliciting feedback post a generally available v1.0 release since by that time it will be too late to change course on certain design aspects that require major (e.g. breaking) changes.
We therefore agreed that a suitable point in time would be anchored to whenever we have had issued our v0.3 release of Cactus.

Purpose/tasks of this GH issue:
1. Make sure this is not forgotten => adding it as a mandatory item for the GitHub milestone v0.4
2. Allow everyone to chime in here even before we hit the v0.3 release so that we have a central place to collect everyone's thoughts (I will also post a link to this issue on the chat and the mailing list)
3. (?) Brainstorm about a discussion framework that we should be using if any. E.g., do we follow a simple approach of shooting an email saying `Dear $LEDGER Maintainer, what do you think of Cactus?` to everyone and hope for the best or do we make it more structured with a survey containing targeted questions?
4. Decide on which ledgers to focus on: Do we talk to ledger maintainers whose ledgers are not yet supported at all? (Sawtooth for example) or do we only talk to the ones we already have at least partial support for via connector plugins?

### Acceptance Criteria
1. Feedback was obtained from the ledger maintainers
2. Feedback was distilled down into design changes and implementation tasks (assuming there will be changes proposed since us getting everything right the first time seems pretty unlikely)

cc: @jonathan-m-hamilton @takeutak @sfuji822 @hartm

**Comment by hartm** [comment]
It was discussed on the TSC call this morning that the TSC was hoping for more technical content during the calls.  In particular, everyone seemed to want about one technical talk a month.

One idea:  should we ask for a TSC technical talk slot where we can solicit this input from the TSC (and the people that attend the meetings)?  We could present on the Cactus architecture and ask people for feedback with regards to connecting to their particular ledger.  It might be the best way to get the attention of people across a wide variety of projects.

What do you all think?

**Comment by jonathan-m-hamilton** [comment]
I agree that's a great way to get visibility, feedback and invite collaboration!  Let's discuss timing in the next maintainers.

**Comment by RafaelAPB** [comment]
+1, @hartm .Looks like a good idea to present the work.

**Comment by petermetz** [comment]
I think the biggest takeaway so far is that the ledger maintainer's most important ask is to not mask/make inaccessible the unique features of the ledgers they maintain (rightfully so I might add).

So, as a next round of meetings we could probably turn it around a bit and ask ledger maintainers what are the features they think are the most widely used (among the features that we don't already support) and then prioritize adding those to the Cactus connectors based on that.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @RafaelAPB

**Comment by petermetz** [comment]
Several meetings have occurred in the meantime where we've talked to ledger maintainers and things seem to be heading in the right direction because our designs are able to support different flavors and algorithms for cross-ledger transactions that are both atomic and non-atomic, escrowed, hash time locked, etc.
