### ISSUE TITLE
build(api-client): generate java, go clients

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#393]
### Description

As a developer I want to not be forced to use the NodeJS/Javascript API client if my primary programming language is something else so that I can achieve high productivity through Cactus no matter the language I'm using.

- This is different from a similar looking issue which discusses the possibility of writing plugins in different languages as well.
- We do not need write much Go/Java code because 99% of it is auto-generated. See the Acceptance criteria 4)

Here is a complete list of programming languages that are supported by the OpenAPI generator (which we can take full advantage of since we are using the OpenAPI specs)
https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages

### Acceptance Criteria
1. Clients for Java and Go are generated as part of the full build
2. Dev builds only build the Typescript API client to remain as fast as possible
3. Publishing of the Java and Go API clients is included in the release process => if I run the release scripts the full build runs and the Java, Go clients are published/made available for public consumption the same way we do with the Typescript API client (it gets published to npm)
4. Client side routing is supported by the Go/Java API clients as well.

cc: @takeutak @sfuji822 @jonathan-m-hamilton

**Comment by petermetz** [comment]
This blew up in complexity because the `oneOf` `allOf` keywords are not universally supported among the different OpenAPI generators the way they are for the `typescript-axios` generator so it's not immediately obvious how to migrate away from these unsupported keywords. The other option is to wait for them to add support (or help them implement it) so that we can just go back to a much lower complexity in the scope of this issue once those generators "just work" out of the box.

**Comment by jagpreetsinghsasan** [comment]
For the Go artifacts, publishing the api-client code (as a commit to cacti github code) itself will act as the artifact, right?
Then we can import it something like 
`import cactus-cmd-api-server "github.com/hyperledger/cacti/packages/cactus-cmd-api-server/src/main/go/generated/openapi/go-client"`
@petermetz is this fine?

**Comment by jagpreetsinghsasan** [comment]
The kotlin jar generation is broken, mostly due to openapi-generator upgrade, will fix those alongwith this issue.

**Comment by petermetz** [comment]
> For the Go artifacts, publishing the api-client code (as a commit to cacti github code) itself will act as the artifact, right? Then we can import it something like `import cactus-cmd-api-server "github.com/hyperledger/cacti/packages/cactus-cmd-api-server/src/main/go/generated/openapi/go-client"` @petermetz is this fine?

@jagpreetsinghsasan Yes, works fine for me. Please open a follow-up issue there to mimic how it is being done for the weaver components (@sandeepnRES wrote some scripts or GH actions to do tag based releases IIRC)

**Comment by jagpreetsinghsasan** [comment]
One of the issues I faced during generating java artifacts was that in `cactus-core-api` openapi specs, we have a field within JWSRecipient termed `protected` which matches with the Java `protected` keyword, thus the generated code cannot produce the respective client JAR
(I will create an issue to address the same, mentioning it for future reference)

**Comment by jagpreetsinghsasan** [comment]
Openapi specs
![image](https://github.com/hyperledger/cacti/assets/56861721/340ba712-069d-49a9-a83a-83e45d818148)

Generated code (throwing errors)
![image](https://github.com/hyperledger/cacti/assets/56861721/bda26e95-3fb9-4b5d-a860-bbda80a76bea)

**Comment by jagpreetsinghsasan** [comment]
JAR parsing for cactus-plugin-htlc-eth-besu fails due to invalid Java code being generated
![image](https://github.com/hyperledger/cacti/assets/56861721/f1451559-6094-4674-b443-c4813cd5348b)

Other devs are also facing the same issue: https://github.com/OpenAPITools/openapi-generator/issues/12556#issuecomment-1702264876

**Comment by jagpreetsinghsasan** [comment]
`connector-iroha` faces yet another bug related to openapi codegen (`<`, `>` signs arent rendered correctly)
https://github.com/OpenAPITools/openapi-generator/issues/11601

![image](https://github.com/hyperledger/cacti/assets/56861721/5cd8fd96-acf8-42f6-8310-71f9c9b2b90e)

**Comment by jagpreetsinghsasan** [comment]
As per the conversation, dropping the java clients from the issue (as the same is already achieved using Kotlin)

**Comment by petermetz** [comment]
> As per the [conversation here](https://github.com/hyperledger/cacti/pull/2973#issuecomment-2119466069), dropping the java clients from the issue (as the same is already achieved using Kotlin)

@jagpreetsinghsasan Thank you!
