### ISSUE TITLE
docs(contributing.md): explain watch script

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#521]
### Description

Currently we have an npm script called `watch` that dramatically speeds up development flows by allowing developers to not have to recompile all packages from scratch every time they make any small change in the code.
Unfortunately this new feature is not yet documented and this issue is here to make sure that changes.

https://github.com/hyperledger/cactus/blob/main/package.json#L14

### Acceptance Criteria
1. Contributing.md and build.md are updated to explain the watch script and how it can be used
2. Caveats are mentioned (one of these IIRC is that an initial build must be done fully before the watch can be used so it's important that the documentation clarifies this right up front to avoid people reporting bugs that they cloned the project, tried to run the watch script and failed)
3. Don't copy paste the documentation written about the watch script, either put it in build.md or contributing.md and then the other one where you choose not to put it can just have a quick sentence mentioning it and linking to the other document which you chose to contain the full explanation.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jagpreetsinghsasan @jordigiam @kikoncuo

**Comment by ggold7046** [comment]
Hi @petermetz , could you please guide me a little more on this as I'm new Hyperledger. How can I solve this problem ?

**Comment by petermetz** [comment]
@ggold7046 Sorry for the slow response! I'm just going through the backlog of issues! We have completed this  while back so I'm closing this down right now. For details on the watch script please take a look at the contributing.md document in the project root!
