### ISSUE TITLE
feat(connector-polkadot): Connector and Validator

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cacti#627]
**Is your feature request related to a problem? Please describe.**
One should be able to connect and interact with Polkadot's nodes and parachains, as it is a raising blockchain of blockchains solution.

**Describe the solution you'd like**
The connector should implement active behavior (deployment, transact) , while the validator should fetch information from the ledger.

**Comment by RafaelAPB** [comment]
Catarina is working on this. We could add this feature to release v1 or v2 @petermetz

**Comment by petermetz** [comment]
@RafaelAPB Added it to the v1.0.0 milestone.

**Comment by RafaelAPB** [comment]
This is implemented at PR #1997, but not (yet) suitable to be merged. Someone can take on the work done so far.

**Comment by jagpreetsinghsasan** [comment]
We will take over from the current progress of the polkadot connector with Anmol Bansal co-authoring to the existing PR (will assign him the tasks soon)

**Comment by AnmolBansalDEV** [comment]
I will be working on this, Thank you!

**Comment by petermetz** [comment]
> I will be working on this, Thank you!

@AnmolBansalDEV Thank you for pushing it over the line!

FYI: I'll also update the commit message in your PR to declare that it fixes this issue.
