### ISSUE TITLE
docs: make docs more accessible & accurate

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger/cacti#64]
### Description
As a user of Cacti, I want to be able to find relevant documentation for my needs.  Cacti has a fair amount of pre-existing documentation, but it is tucked away in ./docs/tutorials/ and has not been updated for open source collaboration.  The objective of this story is to refresh & migrate the existing documentation from the docs to a wiki

### Acceptance Criteria
1. Existing documentation migrated to wiki
2. Documentation updated to reflect point in time state of OSS with expectation of future enhancements)
3. Weaver and Cactus documentation made coherent and unified.

_Note this story is specific to migrating the existing documentation, but there are also separate stories on creating net new documentation_

**Comment by petermetz** [comment]
See also #221

**Comment by kikoncuo** [comment]
Take a look at BAF's way of handling tech state and compatibility
