### ISSUE TITLE
docs(examples): add a Hyperledger Bevel Example

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#65]
### Description
As a user I want to have a working example that uses `Bevel` to pull up an environment so that I have well maintained tooling taking care of the infrastructure from day one of my exploratory journey while checking out what `BIF` can do and once I decide to adopt `BIF` I can roll it out in production with the `Bevel` tooling I'm already comfortable with since that's how I got started to begin with (instead of the partially hand-rolled scripts we currently have for the examples)

Potential dependencies:
1. Does Bevel work on microk8s as of right now? If yes we can probably make the end to end test happen with our github actions running on Ubuntu VMs.

### Acceptance Criteria
1.  `examples/Bevel` directory exists and it has a documented, `Bevel` backed clonse of the current state of the art which is in `examples/simple-asset-transfer`
2. CI also covers the `Bevel` example. This may be hard given that TravisCI has only 8GB RAM and 2 vCPUs

**Comment by jonathan-m-hamilton** [comment]
For those not following the TLAs ;-) 
https://github.com/hyperledger-labs/blockchain-automation-framework

**Comment by jagpreetsinghsasan** [comment]
There are 3 major aspects in solving this,
1. Bevel (using release 1.0 for the referenced code-base) based fabric, besu and quorum networks which can be up and running using simple command(s)/programmatically.
2. Enabling features across Cacti-Bevel codebase for the integrations.
3. A sample application showcasing multiple ledgers interaction.
