### ISSUE TITLE
refactor(cmd-api-server): clean up configuration parameters

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#720]
### Description
As a user of Cactus I don't want to have dangling/zombie configuration parameters in the API server so that I'm not wasting any of my time trying to figure out what they are for or how to use them/provide dummy values to pass the configuration validation mechanism.

Ideally all (or at least most) of the configuration that the API server needs would really just be the configuration that is passed down to the plugin instances so that the API server is kept "dumb" and easily exchangeable.

### Acceptance Criteria
1. The `ConfigService` is cleaned up so that there are no redundant/unused configuration parameters.
2. Documentation is updated
3. API server configuration generation scripts (root package.json for example) are all updated
4. Manual testing verified that the generated configuration does work with the `npm run start:api-server` script (e.g. no crash)
5. Verify that the change is backwards compatible, e.g. the 1.0.0 version of the API server can start with the new reduced configuration file without crashing or producing validation errors
6. If 5) comes back with the outcome that removing these configuration parameters would be a breaking change then label this issue accordingly, e.g. https://github.com/hyperledger/cactus/labels/Breaking_V1

### List of configuration parameters to remove (if they are optional)

- `cactusNodeId`
- `consortiumId`
- `keyPairPem`
- `keychainSuffixKeyPairPem`

**Comment by ruzell22** [comment]
Hello @petermetz , can you assign this to me? Thank you.

**Comment by petermetz** [comment]
> Hello @petermetz , can you assign this to me? Thank you.

@ruzell22 Done, thank you!

**Comment by ruzell22** [comment]
Hello @petermetz , below are the following outputs of different situational tests that I did for the ticket.

After removing keyPairPem:
![Screenshot 2022-04-21 132051 (without keyPairPem error)](https://user-images.githubusercontent.com/89818529/165209225-bbeed52d-2900-4c23-a641-3ebcfb9221e9.png)

Cleaning up based on error log, running npm run configure with successful output but running npm run start: api-server will output an error and it automatically shuts down the API server:
![Screenshot 2022-04-21 132342 (without 4 parameters with better cleaning)](https://user-images.githubusercontent.com/89818529/165209370-8e038ca2-a2e7-4913-9e63-ab3831841556.png)
![Screenshot 2022-04-21 132713 (run start api server with keyPairPem falsy error)](https://user-images.githubusercontent.com/89818529/165209391-d4e4ffff-da33-48aa-b5e8-e12a261020b2.png)

options.keyPairPem falsy and possible code related to the error:
![Screenshot 2022-04-21 132836](https://user-images.githubusercontent.com/89818529/165210334-cf0984ff-8543-4116-b0ef-4ea53d5773a0.png)
![Screenshot 2022-04-21 133031](https://user-images.githubusercontent.com/89818529/165210363-ac5ce06f-1787-4099-b9d5-8a52682d36ce.png)
![Screenshot 2022-04-21 131446](https://user-images.githubusercontent.com/89818529/165210403-db28ec5c-3bec-4b35-8460-fe00e08c1f21.png)

My question for this part is, should I still remove keyPairPem?

Removing the other 3, however, results to a successful npm run configure and npm run start:api-server:
![Screenshot 2022-04-21 140723 (v1 0 0-25-gdda3f00c latest tag npm run configure)](https://user-images.githubusercontent.com/89818529/165211160-99fcc957-e23e-41c3-ba65-e7a55a7f3da6.png)
![Screenshot 2022-04-21 140923 (v1 0 0-25-gdda3f00c tag run api server)](https://user-images.githubusercontent.com/89818529/165211191-0baeb9e7-352e-47d1-89a8-9881c039fac7.png)

**Comment by ruzell22** [comment]
As for backwards compatibility, I first tried it without removing any parameters mentioned and just changing the tags to different version and running npm run configure and npm run start:api-server

v1.0.0-rc1 and v1.0.0-rc.2 both outputs an error in run configure and start:api-server
![Screenshot 2022-04-22 135805 (no changes - v1 0 0-rc 1 tag npm run configure)](https://user-images.githubusercontent.com/89818529/165212128-533684b7-729a-48d7-ab5f-b4a66c3e220e.png)
![Screenshot 2022-04-22 140527 (no changes - v1 0 0 rc-1 - with npm run configure - run start api server)](https://user-images.githubusercontent.com/89818529/165212147-770ee664-3fb9-4daa-9388-a249aeea5569.png)

while v1.0.0-rc.3 outputs a success in run configure and start:api-server
![Screenshot 2022-04-22 142028 (no changes - v1 0 0 rc-3 - npm run configure)](https://user-images.githubusercontent.com/89818529/165212242-26dcae9b-2c14-4b33-a47c-1c0adf8d3cd2.png)
![Screenshot 2022-04-22 142119 (no changes - v1 0 0 rc-3 - with npm run configure - run start api server)](https://user-images.githubusercontent.com/89818529/165212257-8bf0f055-b707-4d17-af5f-23ada5113319.png)

Then I tried doing the same after removing the 3 parameters (excluding keyPairPem):

v1.0.0-rc.1 and v.1.0.0-rc.2 results to an error in run configure and start:api-server:
![Screenshot 2022-04-21 135318 (v1 0 0-rc 1 tag npm run configure error)](https://user-images.githubusercontent.com/89818529/165212471-41b6ff0f-30c0-42e2-9187-369ccac468af.png)
![Screenshot 2022-04-21 135408 (v1 0 0-rc 1 tag api server error)](https://user-images.githubusercontent.com/89818529/165212507-3c7657c5-8089-45fd-891b-d1b4d7e426c6.png)

while v1.0.0-rc.3 resulted to a success in run configure but error in start:api-server
![Screenshot 2022-04-21 140156 (v1 0 0-rc 3 tag npm run configure)](https://user-images.githubusercontent.com/89818529/165212581-88740327-82c1-4074-a1bc-a40454508027.png)
![Screenshot 2022-04-21 140221 (v1 0 0-rc 3 tag run api server error)](https://user-images.githubusercontent.com/89818529/165212606-2daec044-4d8b-42bb-b4ee-887f0d2218a9.png)

excluding the v1.0.0-rc.1 and rc.2, in rc.3, the result differs from each other. Does this mean that removing the parameters is not backwards compatible?

Thank you

**Comment by ruzell22** [comment]
I'm gonna add this detail here for future references. Here are the tests using v1.0.0 tag after cleaning up the parameters mentioned excluding keyPairPem:

npm run configure
![Screenshot 2022-04-28 142344 (with changes - v1 0 0 - npm run configure)](https://user-images.githubusercontent.com/89818529/165729867-13bb76b4-f4ac-48d4-9ee8-f9420fed8702.png)

run start:api-server
![Screenshot 2022-04-28 142433 (with changes - v1 0 0 - with npm run configure - run start api server)](https://user-images.githubusercontent.com/89818529/165729913-19416ab6-847c-4fae-9ae1-6762c47e82c8.png)

**Comment by ruzell22** [comment]
An update on v1.0.0-rc.3 using npm run start:api-server that has a successful output:
![Screenshot 2022-04-29 110339 (with changes - v1 0 0-rc 3 - with npm run configure- run start api server)](https://user-images.githubusercontent.com/89818529/165879416-0d8fc085-00fb-439e-b376-8d17797cf602.png)

**Comment by ruzell22** [comment]
Hello @petermetz , the clean up configuration parameters part of the ticket is already finished and is just having issue with the gitguardian. Since it will not be used anymore, this ticket is finished and can be closed and fixed by #1996 . Thank you.
