### ISSUE TITLE
refactor(build): enabling partial build of sub-moduels

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cacti#721]
**Describe the solution you'd like**
Considering the actual use of CACTUS, it is convenient if the build-rule allows developers to get specific SDKs and sub-modules.

**Additional context**
We should also consider supporting building tools for the ledger plugin implementation which is written in other than Typescript (ex. Rust, go, java).

**Comment by petermetz** [comment]
@sfuji822 Have you tried the `npm run watch` script yet? (for building specific packages that have changes made to them real time)

**Comment by outSH** [comment]
Monorepo setup mandates general setup at least once (to fetch npm packages), later on single packages can be rebuild separately (npx tsc). Closing
