### ISSUE TITLE
feat(connector-polkadot): connector plugin should be able to send transactions to Polkadot

### ISSUE THREAD

**Issue by CatarinaPedreira** [hyperledger/cacti#726]
**Describe the solution you'd like**
The connector plugin should be able to send transactions to the Polkadot network, in order to pay for the distribution of its transactions.

cc: @RafaelAPB

**Comment by petermetz** [comment]
@CatarinaPedreira I recommend looking into potentially also opening a separate issue for the creation of a Polkadot all-in-one container image similar to how we have the ones for the existing ledgers that the connectors support, such as this one for Corda:

Image:
https://github.com/hyperledger/cactus/tree/main/tools/docker/corda-all-in-one 

Test tooling code for the image above:
https://github.com/hyperledger/cactus/tree/main/packages/cactus-test-tooling/src/main/typescript/corda

---

The upside of having these AIO images is that integration tests for the connectors can re-use them for pulling up pristine ledgers with proper test case isolation and other best practices.

cc: @RafaelAPB

**Comment by CatarinaPedreira** [comment]
@petermetz Sounds good! I will create that separate issue.
Thank you :) I'm currently studying the code in order to begin the implementation soon.

cc: @RafaelAPB

**Comment by aruns05** [comment]
@CatarinaPedreira  Are you still working on this. ?

**Comment by aruns05** [comment]
> @petermetz Sounds good! I will create that separate issue.

@CatarinaPedreira Is there a separate issue for this?

**Comment by RafaelAPB** [comment]
@aruns05 i don't think Catarina is working on this, but feel free to take on the WIP that has been done

**Comment by petermetz** [comment]
@RafaelAPB @CatarinaPedreira @aruns05 Kewl, assigning this to @aruns05 in that case because he indicated that he'd like to pick this one up. Thank you in advance for the contributions!

**Comment by aruns05** [comment]
@RafaelAPB   Sorry for delayed response. I have resumed work on this. Can you help me understand to get started. I am looking in this repo https://github.com/RafaelAPB/blockchain-integration-framework/tree/polkadot-connector/packages/cactus-plugin-ledger-connector-polkadot

I am looking at branches polkadot and polkadot-connector, Can we meet sometime this week

**Comment by RafaelAPB** [comment]
@aruns05 please reach out via discord and we can go from there

**Comment by AnmolBansalDEV** [comment]
I will be working on this, Thank you!

**Comment by petermetz** [comment]
> I will be working on this, Thank you!

@AnmolBansalDEV Assigned it to you just now, cheers!

FYI: I'll also update the commit message in your PR to declare that it fixes this issue.
