### ISSUE TITLE
feat(connector-polkadot): connector plugin should be able to deploy smart contracts in Polkadot

### ISSUE THREAD

**Issue by CatarinaPedreira** [hyperledger/cacti#727]
**Describe the solution you'd like**
The connector plugin should be able to deploy smart contracts on a predefined parachain, in the Polkadot network. 

**Describe alternatives you've considered**
Alternatively, the connector plugin can send the necessary information to a predefined parachain on the Polkadot network, which then deploys smart contracts accordingly.

cc: @RafaelAPB

**Comment by AnmolBansalDEV** [comment]
I will be working on this, Thank you!

**Comment by petermetz** [comment]
> I will be working on this, Thank you!

@AnmolBansalDEV Assigned it to you just now, cheers!

FYI: I'll also update the commit message in your PR to declare that it fixes this issue.
