### ISSUE TITLE
feat(tools): Polkadot AIO container image

### ISSUE THREAD

**Issue by CatarinaPedreira** [hyperledger/cacti#773]
**Describe the solution you'd like**
The creation of an all-in-one container image for Polkadot, so that test case isolation and other best practices can take place.

**Additional context**
This will be based on the existing ledgers that the connectors support, such as this one for Corda: https://github.com/hyperledger/cactus/tree/main/tools/docker/corda-all-in-one

**Comment by RafaelAPB** [comment]
This was closed by PR  #1274 https://github.com/hyperledger/cactus/pull/1274
