### ISSUE TITLE
feat(connector-corda): containerize plugin

### ISSUE THREAD

**Issue by jordigiam** [hyperledger/cacti#789]
**Is your feature request related to a problem? Please describe.**

Cloud has became the de-facto way of running applications on computers.
Containers are rapidly becoming (have become?) the de-facto way of running applications in the cloud.
We therefore need to make sure that Cactus is not just built and distributed as the language native artifacts (e.g. npm packages/webpack bundles) but that it's also distributed as containers.
This doesn't just mean containerizing the API server that can host the plugins, but also means containerizing each plugin individually as well OR providing a generic image of the API server that can be configured to run any and all of the available Cactus plugins on-demand.

**Describe the solution you'd like**

I want to be able to whisper things like this to my terminal and expect to have a fully functional connector for Ledger X up and running in a few seconds and with the config.json file mounted at the specified path/volume that gets picked up by the API server running inside the container as well.

```sh
echo "{ \"some-configuration\": 42 } " > config.json

docker run \
  --rm \
  --volume ./config.json:/opt/hyperledger/cactus/cactus-plugin-ledger-connector-corda/config.json \ 
  hyperledger/cactus-plugin-ledger-connector-corda
```

**Acceptance criteria**

1. Dockerfile for generate de docker image with the plugin connector and the api server running.

**Comment by elenaizaguirre** [comment]
I will continue this issue!

**Comment by petermetz** [comment]
@elenaizaguirre Are you still working on this?

**Comment by elenaizaguirre** [comment]
> @elenaizaguirre Are you still working on this? And if yes, are you working directly on Jordi's old branch (#805) or did you start a new one?

@petermetz Sorry, I completely forgot this issue. I can work on it when I finish the one I'm working on.

**Comment by petermetz** [comment]
@elenaizaguirre No worries, it's easy to lose track. Recently, I've been using the VSCode GitHub extension to keep track of assigned issues/old PRs and it's been much easier through that compared to the web UI so I recommend you give it a try too if you are interested.

**Comment by petermetz** [comment]
Closing this down for now because it's for Corda v4 but we are focusing on Corda v5.
