### ISSUE TITLE
docs(business-logic-plugin): Create README file

### ISSUE THREAD

**Issue by AzaharaC** [hyperledger/cacti#831]
**Description.**
As a potential user of Cactus I want to have documentation of what and how this package is used.

**Describe the solution you'd like.**
Add a README.md file in the packages/business-logic-plugin folder with this package usage information.

**Acceptance criteria.**
The README file exists and contains the package information.

**Comment by sfuji822** [comment]
I agree with the need for documentation, but I want to organize them inside of the docs directory. 
The reason I thought that way is the modules directory is the place to put module codes, but not the place to use them.
@AzaharaC

**Comment by petermetz** [comment]
Closing this for now due to lack of time. We can re-open it in the future as needed.
