### ISSUE TITLE
feat(connector-fabric): pre-signed transactions support

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#858]
**Is your feature request related to a problem? Please describe.**

Pre-signed trasanctions or offline signed transactions are a way for users not to have to have their keys exposed to the Cactus API server / connector plugin at all.
Currently we do not support this but we should.

**Describe the solution you'd like**

Follow the lead from how it's done on the Web3 flavored connectors with different types of signing credentials being enumerated in the OpenAPI spec and then used by the connector to decide at runtime which way the run transaction requests should be served. 

**Describe alternatives you've considered**

None, I'm confident we need this and in this way.

**Additional context**

Relevant issue (same thing) in the carbon accounting tool's issue tracker:
https://github.com/hyperledger-labs/blockchain-carbon-accounting/issues/11

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan @arnab-roy

**Comment by outSH** [comment]
Offline signing in fabric implemented some time ago
