### ISSUE TITLE
refactor(Validator): update Fabric Validator dealing Fabric transactions

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cacti#871]
**Is your feature request related to a problem? Please describe.**
In some cases, the 2-step transaction posting process of Fabric cannot communicate properly, so I will correct it.

**Describe the solution you'd like**
To update the codes.

**Comment by divyamerlin22** [comment]
Dear sir,

any updation in second step transaction process of fabric communication to the fabric blockchain

**Comment by outSH** [comment]
fabric-socketio connector removed
