### ISSUE TITLE
feat(connector-fabric): external chain code deployment

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#916]
**Is your feature request related to a problem? Please describe.**

Currently the deploy contract endpoint of the Fabric connector does not support external chain code deployment and that is a problem because microk8s does not support Docker as the OCI runtime anymore.

More info here: https://github.com/hyperledger/cactus/issues/911#issuecomment-831671428

**Describe the solution you'd like**

First some analysis should be done to see if it even makes sense for us to support external chain code deployment or if it makes more sense to pass on this because it would make Cactus too involved with infrastructure related matters which we want to avoid.

1.  A new class called `ExternalChaincodeDeployer` or similar with the method of `deploy(req: DeployContractExternalV1Request): Promise<DeployContractExternalV1Response>
2. On the plugin class there should be a new method that instantiates the class above and calls into it to make things happen.
3. Endpoint class as usual
4. OpenAPI spec file updated with a new endpoint as usual
5. End to end tests verifying that the new feature works.

**Describe alternatives you've considered**

I still am considering whether this should be in scope or not.

**Additional context**

https://github.com/hyperledger/cactus/issues/911#issuecomment-831671428

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @jagpreetsinghsasan

**Comment by RafaelAPB** [comment]
Could you elaborate on what is external chaincode deployment? You mean Chaincode as an external service?

https://hyperledger-fabric.readthedocs.io/en/release-2.2/cc_service.html

**Comment by petermetz** [comment]
@RafaelAPB Yes, that's what I meant (I think). The mode of deployment when the peer doesn't launch the container itself but instead just receives some environment variable about where the chaincode is running and then it talks to it through that.

**Comment by petermetz** [comment]
Closing this for now due to lack of time. We can re-open it in the future if there's demand/time to work on it.
