### ISSUE TITLE
bug(ledger-plugin): Consistency with design principle on behavior of HTLC 

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cacti#957]
**Describe the bug**

series of PRs started from PR#587 is inconsistent with the design principle described in section 4.1.5 Low Impact https://github.com/hyperledger/cactus/blob/main/whitepaper/whitepaper.md#415-low-impact .
IMHO, Cactus should not change the rule on the DLT world which is interworking with the Cactus Node.
It came from the existence of API to allow deploy smart contracts described in section 5.6 of the white paper. 

**Expected behavior**

Any smart contract should not be deployed by system programs that belong to the Cactus Node for the governance of DLTs.
HTLC feature should be re-designed not to assume the deployment of Smart contract for expected behavior.

**Comment by petermetz** [comment]
@sfuji822 Could they both co-exist so that if a user prefers to have on-chain contracts they can still have their way?

**Comment by sfuji822** [comment]
[proposed-flow.md](https://github.com/hyperledger/cactus/files/6478166/proposed-flow.md)
This is an example flow that implements Atomic Swap with re-usable HTLC contracts with more control on user-side.

**Comment by sfuji822** [comment]
Is there any comment on the above?
@petermetz @kikoncuo

**Comment by petermetz** [comment]
@sfuji822 I'll let @kikoncuo chime in.

**Comment by kikoncuo** [comment]
@sfuji822 Apologies for the delay, 
We updated the PR we are using re-usable smart contracts and have taken out the concept of the coordinator to give more control on the user side.
Once the PRs are ready we will provide specific examples in the code to showcase for easier review
