### ISSUE TITLE
feat(fabric-connector): obtain blocks and transaction data

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cacti#958]
**Is your feature request related to a problem? Please describe.**
As a researcher, I would like to be able to obtain raw data for transactions and blocks from Fabric's network.

**Describe the solution you'd like**
Add methods to the Fabric Connector

**Describe alternatives you've considered**
Manually using Docker

**Comment by outSH** [comment]
`getBlock` / `GetBlockEndpointV1` can be used to get raw block data from ledger now so closing. In case it's not what you need please let me know and I will reopen this
