### ISSUE TITLE
feat(connector): remove hard dependency on keychain 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#963]
### Description
As a user of Cactus I want to be able to omit using the keychain if I want to so that I can pick and chose what complexity I take on when I decide to use the framework for my project.

https://chat.hyperledger.org/channel/cactus?msg=WgTabjQho3oFGskSa

### Acceptance Criteria
1. Test coverage for both with and without keychain scenarios
2. CI suite passing
3. Avoid depending on shared mutable state, the API server must be horizontally scalable. No file system usage either.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @jagpreetsinghsasan @TonyRowntree @travis-payne

**Comment by elenaizaguirre** [comment]
@TonyRowntree You need to pass this issue to someone, right?

**Comment by TonyRowntree** [comment]
@elenaizaguirre I will be continuing with the fabric one and (hopefully) get it finished by end of week. The xdai one is up for grabs so feel free to take it if you like :)

**Comment by elenaizaguirre** [comment]
@TonyRowntree Thank you, I´ll take it

**Comment by petermetz** [comment]
@elenaizaguirre @TonyRowntree Thank you for coordinating on this!
